services:
  # -------------------------
  # PostgreSQL Database
  # -------------------------
  db:
    image: postgres:latest
    container_name: PostgreSQL_DB
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER_SECRET}
      POSTGRES_PASSWORD: ${DB_PASSWORD_SECRET}
      POSTGRES_DB: ${DB_NAME_SECRET}
    ports:
      - "5432:5432"
    volumes:
      # מיפוי קובץ היצירה - ניתן לו מספר 01 כדי שירוץ ראשון
      - ./"Step 1"/createTables.sql:/docker-entrypoint-initdb.d/01_createTables.sql
      # מיפוי קובץ הכנסת הנתונים - ניתן לו מספר 02 כדי שירוץ שני
      - ./"Step 1"/insertTables.sql:/docker-entrypoint-initdb.d/02_insertTables.sql
      # שמירת הנתונים
      - postgres_data:/var/lib/postgresql
    networks:
      - ramilevi_network

  # -------------------------
  # pgAdmin
  # -------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminApp
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - ramilevi_network

# -------------------------
# Volumes
# -------------------------
volumes:
  postgres_data:
  pgadmin_data:

networks:
  ramilevi_network: