INSERT INTO CATEGORY (CategoryID, CategoryName, IsActive) VALUES
(1, 'Milk and Dairy Products', 1),
(2, 'Yellow Cheeses', 1),
(3, 'Soft Cheeses', 1),
(4, 'Yogurts', 1),
(5, 'Dairy Desserts', 1),
(6, 'Butter and Spreads', 1),
(7, 'Eggs', 1),
(8, 'White Bread', 1),
(9, 'Whole Grain Bread', 1),
(10, 'Pita and Laffa', 1),
(11, 'Rolls and Buns', 1),
(12, 'Cakes', 1),
(13, 'Cookies and Biscuits', 1),
(14, 'Crackers', 1),
(15, 'Breakfast Cereals', 1),
(16, 'Granola and Oats', 1),
(17, 'Pasta', 1),
(18, 'Rice', 1),
(19, 'Legumes', 1),
(20, 'Flour and Baking Ingredients', 1),
(21, 'Cooking Oils', 1),
(22, 'Sauces and Condiments', 1),
(23, 'Spices and Seasonings', 1),
(24, 'Coffee and Hot Drinks', 1),
(25, 'Soft Drinks', 1),
(26, 'Fruit Juices', 1),
(27, 'Water and Soda', 1),
(28, 'Energy Drinks', 1),
(29, 'Savory Snacks', 1),
(30, 'Chocolate and Candy', 1),
(31, 'Nuts and Seeds', 1),
(32, 'Apples and Pears', 1),
(33, 'Bananas', 1),
(34, 'Citrus Fruits', 1),
(35, 'Tropical Fruits', 1),
(36, 'Seasonal Fruits', 1),
(37, 'Tomatoes', 1),
(38, 'Cucumbers', 1),
(39, 'Peppers', 1),
(40, 'Leafy Greens', 1),
(41, 'Root Vegetables', 1),
(42, 'Onions and Garlic', 1),
(43, 'Potatoes and Sweet Potatoes', 1),
(44, 'Fresh Herbs', 1),
(45, 'Mushrooms', 1),
(46, 'Fresh Beef', 1),
(47, 'Ground Beef and Burgers', 1),
(48, 'Fresh Chicken', 1),
(49, 'Chicken Cuts', 1),
(50, 'Turkey Products', 1),
(51, 'Fresh Fish', 1),
(52, 'Frozen Fish', 1),
(53, 'Canned Fish', 1),
(54, 'Sausages and Deli Meats', 1),
(55, 'Prepared Salads', 1),
(56, 'Hummus Tahini and Dips', 1),
(57, 'Frozen Vegetables', 1),
(58, 'Frozen Pastries', 1),
(59, 'Frozen Meals', 1),
(60, 'Frozen Pizza', 1),
(61, 'Ice Cream and Popsicles', 1),
(62, 'Baby Food', 1),
(63, 'Infant Cereals', 1),
(64, 'Gluten Free Products', 1),
(65, 'Vegan Products', 1),
(66, 'Plant Based Milk Alternatives', 1),
(67, 'Canned Vegetables', 1),
(68, 'Canned Fruits', 1),
(69, 'Jams and Honey', 1),
(70, 'Pickles and Olives', 1),
(71, 'Matzah and Holiday Crackers', 1),
(72, 'Baking Mixes', 1),
(73, 'Instant Meals and Soups', 1),
(74, 'Coffee Capsules', 1),
(75, 'Tea and Herbal Infusions', 1),
(76, 'Sandwich Breads', 1),
(77, 'Tortillas and Wraps', 1),
(78, 'Asian Noodles', 1),
(79, 'Couscous and Ptitim', 1),
(80, 'Ready To Eat Meals', 1),
(81, 'Premium Meats', 1),
(82, 'Smoked Fish', 1),
(83, 'Cheese Spreads', 1),
(84, 'Cream and Whipping Products', 1),
(85, 'Chocolate Spreads', 1),
(86, 'Nut Butters and Spreads', 1),
(87, 'Protein Bars', 1),
(88, 'Rice Cakes', 1),
(89, 'Salt Sugar and Sweeteners', 1),
(90, 'Dried Fruits', 1),
(91, 'Sports Drinks', 1),
(92, 'Sparkling Drinks', 1),
(93, 'Breakfast Pastries', 1),
(94, 'Savory Pastries', 1),
(95, 'Frozen Desserts', 1),
(96, 'Table Olives and Antipasti', 1),
(97, 'Gourmet Sauces', 1),
(98, 'Specialty Grains', 1),
(99, 'Ready Baking Products', 1),
(100, 'Healthy Snacks', 1);

INSERT INTO CATEGORY (CategoryID, CategoryName, IsActive) VALUES
(101, 'Organic Milk and Dairy Products', 1),
(102, 'Organic Yellow Cheeses', 1),
(103, 'Organic Soft Cheeses', 1),
(104, 'Organic Yogurts', 1),
(105, 'Organic Dairy Desserts', 1),
(106, 'Organic Butter and Spreads', 1),
(107, 'Organic Eggs', 1),
(108, 'Organic White Bread', 1),
(109, 'Organic Whole Grain Bread', 1),
(110, 'Organic Pita and Laffa', 1),
(111, 'Organic Rolls and Buns', 1),
(112, 'Organic Cakes', 1),
(113, 'Organic Cookies and Biscuits', 1),
(114, 'Organic Crackers', 1),
(115, 'Organic Breakfast Cereals', 1),
(116, 'Organic Granola and Oats', 1),
(117, 'Organic Pasta', 1),
(118, 'Organic Rice', 1),
(119, 'Organic Legumes', 1),
(120, 'Organic Flour and Baking Ingredients', 1),
(121, 'Organic Cooking Oils', 1),
(122, 'Organic Sauces and Condiments', 1),
(123, 'Organic Spices and Seasonings', 1),
(124, 'Organic Coffee and Hot Drinks', 1),
(125, 'Organic Soft Drinks', 1),
(126, 'Organic Fruit Juices', 1),
(127, 'Organic Water and Soda', 1),
(128, 'Organic Energy Drinks', 1),
(129, 'Organic Savory Snacks', 1),
(130, 'Organic Chocolate and Candy', 1),
(131, 'Organic Nuts and Seeds', 1),
(132, 'Organic Apples and Pears', 1),
(133, 'Organic Bananas', 1),
(134, 'Organic Citrus Fruits', 1),
(135, 'Organic Tropical Fruits', 1),
(136, 'Organic Seasonal Fruits', 1),
(137, 'Organic Tomatoes', 1),
(138, 'Organic Cucumbers', 1),
(139, 'Organic Peppers', 1),
(140, 'Organic Leafy Greens', 1),
(141, 'Organic Root Vegetables', 1),
(142, 'Organic Onions and Garlic', 1),
(143, 'Organic Potatoes and Sweet Potatoes', 1),
(144, 'Organic Fresh Herbs', 1),
(145, 'Organic Mushrooms', 1),
(146, 'Organic Fresh Beef', 1),
(147, 'Organic Ground Beef and Burgers', 1),
(148, 'Organic Fresh Chicken', 1),
(149, 'Organic Chicken Cuts', 1),
(150, 'Organic Turkey Products', 1),
(151, 'Organic Fresh Fish', 1),
(152, 'Organic Frozen Fish', 1),
(153, 'Organic Canned Fish', 1),
(154, 'Organic Sausages and Deli Meats', 1),
(155, 'Organic Prepared Salads', 1),
(156, 'Organic Hummus Tahini and Dips', 1),
(157, 'Organic Frozen Vegetables', 1),
(158, 'Organic Frozen Pastries', 1),
(159, 'Organic Frozen Meals', 1),
(160, 'Organic Frozen Pizza', 1),
(161, 'Organic Ice Cream and Popsicles', 1),
(162, 'Organic Baby Food', 1),
(163, 'Organic Infant Cereals', 1),
(164, 'Organic Gluten Free Products', 1),
(165, 'Organic Vegan Products', 1),
(166, 'Organic Plant Based Milk Alternatives', 1),
(167, 'Organic Canned Vegetables', 1),
(168, 'Organic Canned Fruits', 1),
(169, 'Organic Jams and Honey', 1),
(170, 'Organic Pickles and Olives', 1),
(171, 'Organic Matzah and Holiday Crackers', 1),
(172, 'Organic Baking Mixes', 1),
(173, 'Organic Instant Meals and Soups', 1),
(174, 'Organic Coffee Capsules', 1),
(175, 'Organic Tea and Herbal Infusions', 1),
(176, 'Organic Sandwich Breads', 1),
(177, 'Organic Tortillas and Wraps', 1),
(178, 'Organic Asian Noodles', 1),
(179, 'Organic Couscous and Ptitim', 1),
(180, 'Organic Ready To Eat Meals', 1),
(181, 'Organic Premium Meats', 1),
(182, 'Organic Smoked Fish', 1),
(183, 'Organic Cheese Spreads', 1),
(184, 'Organic Cream and Whipping Products', 1),
(185, 'Organic Chocolate Spreads', 1),
(186, 'Organic Nut Butters and Spreads', 1),
(187, 'Organic Protein Bars', 1),
(188, 'Organic Rice Cakes', 1),
(189, 'Organic Salt Sugar and Sweeteners', 1),
(190, 'Organic Dried Fruits', 1),
(191, 'Organic Sports Drinks', 1),
(192, 'Organic Sparkling Drinks', 1),
(193, 'Organic Breakfast Pastries', 1),
(194, 'Organic Savory Pastries', 1),
(195, 'Organic Frozen Desserts', 1),
(196, 'Organic Table Olives and Antipasti', 1),
(197, 'Organic Gourmet Sauces', 1),
(198, 'Organic Specialty Grains', 1),
(199, 'Organic Ready Baking Products', 1),
(200, 'Organic Healthy Snacks', 1);

INSERT INTO CATEGORY (CategoryID, CategoryName, IsActive) VALUES
(201, 'Kosher for Passover Milk and Dairy Products', 1),
(202, 'Kosher for Passover Yellow Cheeses', 1),
(203, 'Kosher for Passover Soft Cheeses', 1),
(204, 'Kosher for Passover Yogurts', 1),
(205, 'Kosher for Passover Dairy Desserts', 1),
(206, 'Kosher for Passover Butter and Spreads', 1),
(207, 'Kosher for Passover Eggs', 1),
(208, 'Kosher for Passover White Bread Alternatives', 1),
(209, 'Kosher for Passover Whole Grain Bread Alternatives', 1),
(210, 'Kosher for Passover Rolls and Buns Alternatives', 1),
(211, 'Kosher for Passover Cakes', 1),
(212, 'Kosher for Passover Cookies and Biscuits', 1),
(213, 'Kosher for Passover Crackers', 1),
(214, 'Kosher for Passover Breakfast Cereals', 1),
(215, 'Kosher for Passover Granola and Oats', 1),
(216, 'Kosher for Passover Pasta Alternatives', 1),
(217, 'Kosher for Passover Rice', 1),
(218, 'Kosher for Passover Legumes', 1),
(219, 'Kosher for Passover Flour and Baking Ingredients', 1),
(220, 'Kosher for Passover Cooking Oils', 1),
(221, 'Kosher for Passover Sauces and Condiments', 1),
(222, 'Kosher for Passover Spices and Seasonings', 1),
(223, 'Kosher for Passover Coffee and Hot Drinks', 1),
(224, 'Kosher for Passover Soft Drinks', 1),
(225, 'Kosher for Passover Fruit Juices', 1),
(226, 'Kosher for Passover Water and Soda', 1),
(227, 'Kosher for Passover Energy Drinks', 1),
(228, 'Kosher for Passover Savory Snacks', 1),
(229, 'Kosher for Passover Chocolate and Candy', 1),
(230, 'Kosher for Passover Nuts and Seeds', 1),
(231, 'Kosher for Passover Apples and Pears', 1),
(232, 'Kosher for Passover Bananas', 1),
(233, 'Kosher for Passover Citrus Fruits', 1),
(234, 'Kosher for Passover Tropical Fruits', 1),
(235, 'Kosher for Passover Seasonal Fruits', 1),
(236, 'Kosher for Passover Tomatoes', 1),
(237, 'Kosher for Passover Cucumbers', 1),
(238, 'Kosher for Passover Peppers', 1),
(239, 'Kosher for Passover Leafy Greens', 1),
(240, 'Kosher for Passover Root Vegetables', 1),
(241, 'Kosher for Passover Onions and Garlic', 1),
(242, 'Kosher for Passover Potatoes and Sweet Potatoes', 1),
(243, 'Kosher for Passover Fresh Herbs', 1),
(244, 'Kosher for Passover Mushrooms', 1),
(245, 'Kosher for Passover Fresh Beef', 1),
(246, 'Kosher for Passover Ground Beef and Burgers', 1),
(247, 'Kosher for Passover Fresh Chicken', 1),
(248, 'Kosher for Passover Chicken Cuts', 1),
(249, 'Kosher for Passover Turkey Products', 1),
(250, 'Kosher for Passover Fresh Fish', 1),
(251, 'Kosher for Passover Frozen Fish', 1),
(252, 'Kosher for Passover Canned Fish', 1),
(253, 'Kosher for Passover Sausages and Deli Meats', 1),
(254, 'Kosher for Passover Prepared Salads', 1),
(255, 'Kosher for Passover Hummus Tahini and Dips', 1),
(256, 'Kosher for Passover Frozen Vegetables', 1),
(257, 'Kosher for Passover Frozen Pastries', 1),
(258, 'Kosher for Passover Frozen Meals', 1),
(259, 'Kosher for Passover Frozen Pizza Alternatives', 1),
(260, 'Kosher for Passover Ice Cream and Popsicles', 1),
(261, 'Kosher for Passover Baby Food', 1),
(262, 'Kosher for Passover Infant Cereals', 1),
(263, 'Kosher for Passover Gluten Free Products', 1),
(264, 'Kosher for Passover Vegan Products', 1),
(265, 'Kosher for Passover Plant Based Milk Alternatives', 1),
(266, 'Kosher for Passover Canned Vegetables', 1),
(267, 'Kosher for Passover Canned Fruits', 1),
(268, 'Kosher for Passover Jams and Honey', 1),
(269, 'Kosher for Passover Pickles and Olives', 1),
(270, 'Kosher for Passover Matzah and Holiday Crackers', 1),
(271, 'Kosher for Passover Baking Mixes', 1),
(272, 'Kosher for Passover Instant Meals and Soups', 1),
(273, 'Kosher for Passover Coffee Capsules', 1),
(274, 'Kosher for Passover Tea and Herbal Infusions', 1),
(275, 'Kosher for Passover Sandwich Bread Alternatives', 1),
(276, 'Kosher for Passover Tortilla Alternatives', 1),
(277, 'Kosher for Passover Asian Noodle Alternatives', 1),
(278, 'Kosher for Passover Couscous and Ptitim Alternatives', 1),
(279, 'Kosher for Passover Ready To Eat Meals', 1),
(280, 'Kosher for Passover Premium Meats', 1),
(281, 'Kosher for Passover Smoked Fish', 1),
(282, 'Kosher for Passover Cheese Spreads', 1),
(283, 'Kosher for Passover Cream and Whipping Products', 1),
(284, 'Kosher for Passover Chocolate Spreads', 1),
(285, 'Kosher for Passover Nut Butters and Spreads', 1),
(286, 'Kosher for Passover Protein Bars', 1),
(287, 'Kosher for Passover Rice Cakes', 1),
(288, 'Kosher for Passover Salt Sugar and Sweeteners', 1),
(289, 'Kosher for Passover Dried Fruits', 1),
(290, 'Kosher for Passover Sports Drinks', 1),
(291, 'Kosher for Passover Sparkling Drinks', 1),
(292, 'Kosher for Passover Breakfast Pastries', 1),
(293, 'Kosher for Passover Savory Pastries', 1),
(294, 'Kosher for Passover Frozen Desserts', 1),
(295, 'Kosher for Passover Table Olives and Antipasti', 1),
(296, 'Kosher for Passover Gourmet Sauces', 1),
(297, 'Kosher for Passover Specialty Grains', 1),
(298, 'Kosher for Passover Ready Baking Products', 1),
(299, 'Kosher for Passover Healthy Snacks', 1),
(300, 'Kosher for Passover Holiday Foods', 1);

INSERT INTO CATEGORY (CategoryID, CategoryName, IsActive) VALUES
(301, 'Sugar Free Milk and Dairy Products', 1),
(302, 'Sugar Free Yellow Cheeses', 1),
(303, 'Sugar Free Soft Cheeses', 1),
(304, 'Sugar Free Yogurts', 1),
(305, 'Sugar Free Dairy Desserts', 1),
(306, 'Sugar Free Butter and Spreads', 1),
(307, 'Sugar Free Eggs', 1),
(308, 'Sugar Free White Bread', 1),
(309, 'Sugar Free Whole Grain Bread', 1),
(310, 'Sugar Free Pita and Laffa', 1),
(311, 'Sugar Free Rolls and Buns', 1),
(312, 'Sugar Free Cakes', 1),
(313, 'Sugar Free Cookies and Biscuits', 1),
(314, 'Sugar Free Crackers', 1),
(315, 'Sugar Free Breakfast Cereals', 1),
(316, 'Sugar Free Granola and Oats', 1),
(317, 'Sugar Free Pasta', 1),
(318, 'Sugar Free Rice', 1),
(319, 'Sugar Free Legumes', 1),
(320, 'Sugar Free Flour and Baking Ingredients', 1),
(321, 'Sugar Free Cooking Oils', 1),
(322, 'Sugar Free Sauces and Condiments', 1),
(323, 'Sugar Free Spices and Seasonings', 1),
(324, 'Sugar Free Coffee and Hot Drinks', 1),
(325, 'Sugar Free Soft Drinks', 1),
(326, 'Sugar Free Fruit Juices', 1),
(327, 'Sugar Free Water and Soda', 1),
(328, 'Sugar Free Energy Drinks', 1),
(329, 'Sugar Free Savory Snacks', 1),
(330, 'Sugar Free Chocolate and Candy', 1),
(331, 'Sugar Free Nuts and Seeds', 1),
(332, 'Sugar Free Apples and Pears', 1),
(333, 'Sugar Free Bananas', 1),
(334, 'Sugar Free Citrus Fruits', 1),
(335, 'Sugar Free Tropical Fruits', 1),
(336, 'Sugar Free Seasonal Fruits', 1),
(337, 'Sugar Free Tomatoes', 1),
(338, 'Sugar Free Cucumbers', 1),
(339, 'Sugar Free Peppers', 1),
(340, 'Sugar Free Leafy Greens', 1),
(341, 'Sugar Free Root Vegetables', 1),
(342, 'Sugar Free Onions and Garlic', 1),
(343, 'Sugar Free Potatoes and Sweet Potatoes', 1),
(344, 'Sugar Free Fresh Herbs', 1),
(345, 'Sugar Free Mushrooms', 1),
(346, 'Sugar Free Fresh Beef', 1),
(347, 'Sugar Free Ground Beef and Burgers', 1),
(348, 'Sugar Free Fresh Chicken', 1),
(349, 'Sugar Free Chicken Cuts', 1),
(350, 'Sugar Free Turkey Products', 1),
(351, 'Sugar Free Fresh Fish', 1),
(352, 'Sugar Free Frozen Fish', 1),
(353, 'Sugar Free Canned Fish', 1),
(354, 'Sugar Free Sausages and Deli Meats', 1),
(355, 'Sugar Free Prepared Salads', 1),
(356, 'Sugar Free Hummus Tahini and Dips', 1),
(357, 'Sugar Free Frozen Vegetables', 1),
(358, 'Sugar Free Frozen Pastries', 1),
(359, 'Sugar Free Frozen Meals', 1),
(360, 'Sugar Free Frozen Pizza', 1),
(361, 'Sugar Free Ice Cream and Popsicles', 1),
(362, 'Sugar Free Baby Food', 1),
(363, 'Sugar Free Infant Cereals', 1),
(364, 'Sugar Free Gluten Free Products', 1),
(365, 'Sugar Free Vegan Products', 1),
(366, 'Sugar Free Plant Based Milk Alternatives', 1),
(367, 'Sugar Free Canned Vegetables', 1),
(368, 'Sugar Free Canned Fruits', 1),
(369, 'Sugar Free Jams and Honey Alternatives', 1),
(370, 'Sugar Free Pickles and Olives', 1),
(371, 'Sugar Free Matzah and Holiday Crackers', 1),
(372, 'Sugar Free Baking Mixes', 1),
(373, 'Sugar Free Instant Meals and Soups', 1),
(374, 'Sugar Free Coffee Capsules', 1),
(375, 'Sugar Free Tea and Herbal Infusions', 1),
(376, 'Sugar Free Sandwich Breads', 1),
(377, 'Sugar Free Tortillas and Wraps', 1),
(378, 'Sugar Free Asian Noodles', 1),
(379, 'Sugar Free Couscous and Ptitim', 1),
(380, 'Sugar Free Ready To Eat Meals', 1),
(381, 'Sugar Free Premium Meats', 1),
(382, 'Sugar Free Smoked Fish', 1),
(383, 'Sugar Free Cheese Spreads', 1),
(384, 'Sugar Free Cream and Whipping Products', 1),
(385, 'Sugar Free Chocolate Spreads', 1),
(386, 'Sugar Free Nut Butters and Spreads', 1),
(387, 'Sugar Free Protein Bars', 1),
(388, 'Sugar Free Rice Cakes', 1),
(389, 'Sugar Free Salt Sugar and Sweeteners', 1),
(390, 'Sugar Free Dried Fruits', 1),
(391, 'Sugar Free Sports Drinks', 1),
(392, 'Sugar Free Sparkling Drinks', 1),
(393, 'Sugar Free Breakfast Pastries', 1),
(394, 'Sugar Free Savory Pastries', 1),
(395, 'Sugar Free Frozen Desserts', 1),
(396, 'Sugar Free Table Olives and Antipasti', 1),
(397, 'Sugar Free Gourmet Sauces', 1),
(398, 'Sugar Free Specialty Grains', 1),
(399, 'Sugar Free Ready Baking Products', 1),
(400, 'Sugar Free Healthy Snacks', 1);

INSERT INTO CATEGORY (CategoryID, CategoryName, IsActive) VALUES
(401, 'Mehadrin Milk and Dairy Products', 1),
(402, 'Mehadrin Yellow Cheeses', 1),
(403, 'Mehadrin Soft Cheeses', 1),
(404, 'Mehadrin Yogurts', 1),
(405, 'Mehadrin Dairy Desserts', 1),
(406, 'Mehadrin Butter and Spreads', 1),
(407, 'Mehadrin Eggs', 1),
(408, 'Mehadrin White Bread', 1),
(409, 'Mehadrin Whole Grain Bread', 1),
(410, 'Mehadrin Pita and Laffa', 1),
(411, 'Mehadrin Rolls and Buns', 1),
(412, 'Mehadrin Cakes', 1),
(413, 'Mehadrin Cookies and Biscuits', 1),
(414, 'Mehadrin Crackers', 1),
(415, 'Mehadrin Breakfast Cereals', 1),
(416, 'Mehadrin Granola and Oats', 1),
(417, 'Mehadrin Pasta', 1),
(418, 'Mehadrin Rice', 1),
(419, 'Mehadrin Legumes', 1),
(420, 'Mehadrin Flour and Baking Ingredients', 1),
(421, 'Mehadrin Cooking Oils', 1),
(422, 'Mehadrin Sauces and Condiments', 1),
(423, 'Mehadrin Spices and Seasonings', 1),
(424, 'Mehadrin Coffee and Hot Drinks', 1),
(425, 'Mehadrin Soft Drinks', 1),
(426, 'Mehadrin Fruit Juices', 1),
(427, 'Mehadrin Water and Soda', 1),
(428, 'Mehadrin Energy Drinks', 1),
(429, 'Mehadrin Savory Snacks', 1),
(430, 'Mehadrin Chocolate and Candy', 1),
(431, 'Mehadrin Nuts and Seeds', 1),
(432, 'Mehadrin Apples and Pears', 1),
(433, 'Mehadrin Bananas', 1),
(434, 'Mehadrin Citrus Fruits', 1),
(435, 'Mehadrin Tropical Fruits', 1),
(436, 'Mehadrin Seasonal Fruits', 1),
(437, 'Mehadrin Tomatoes', 1),
(438, 'Mehadrin Cucumbers', 1),
(439, 'Mehadrin Peppers', 1),
(440, 'Mehadrin Leafy Greens', 1),
(441, 'Mehadrin Root Vegetables', 1),
(442, 'Mehadrin Onions and Garlic', 1),
(443, 'Mehadrin Potatoes and Sweet Potatoes', 1),
(444, 'Mehadrin Fresh Herbs', 1),
(445, 'Mehadrin Mushrooms', 1),
(446, 'Mehadrin Fresh Beef', 1),
(447, 'Mehadrin Ground Beef and Burgers', 1),
(448, 'Mehadrin Fresh Chicken', 1),
(449, 'Mehadrin Chicken Cuts', 1),
(450, 'Mehadrin Turkey Products', 1),
(451, 'Mehadrin Fresh Fish', 1),
(452, 'Mehadrin Frozen Fish', 1),
(453, 'Mehadrin Canned Fish', 1),
(454, 'Mehadrin Sausages and Deli Meats', 1),
(455, 'Mehadrin Prepared Salads', 1),
(456, 'Mehadrin Hummus Tahini and Dips', 1),
(457, 'Mehadrin Frozen Vegetables', 1),
(458, 'Mehadrin Frozen Pastries', 1),
(459, 'Mehadrin Frozen Meals', 1),
(460, 'Mehadrin Frozen Pizza', 1),
(461, 'Mehadrin Ice Cream and Popsicles', 1),
(462, 'Mehadrin Baby Food', 1),
(463, 'Mehadrin Infant Cereals', 1),
(464, 'Mehadrin Gluten Free Products', 1),
(465, 'Mehadrin Vegan Products', 1),
(466, 'Mehadrin Plant Based Milk Alternatives', 1),
(467, 'Mehadrin Canned Vegetables', 1),
(468, 'Mehadrin Canned Fruits', 1),
(469, 'Mehadrin Jams and Honey', 1),
(470, 'Mehadrin Pickles and Olives', 1),
(471, 'Mehadrin Matzah and Holiday Crackers', 1),
(472, 'Mehadrin Baking Mixes', 1),
(473, 'Mehadrin Instant Meals and Soups', 1),
(474, 'Mehadrin Coffee Capsules', 1),
(475, 'Mehadrin Tea and Herbal Infusions', 1),
(476, 'Mehadrin Sandwich Breads', 1),
(477, 'Mehadrin Tortillas and Wraps', 1),
(478, 'Mehadrin Asian Noodles', 1),
(479, 'Mehadrin Couscous and Ptitim', 1),
(480, 'Mehadrin Ready To Eat Meals', 1),
(481, 'Mehadrin Premium Meats', 1),
(482, 'Mehadrin Smoked Fish', 1),
(483, 'Mehadrin Cheese Spreads', 1),
(484, 'Mehadrin Cream and Whipping Products', 1),
(485, 'Mehadrin Chocolate Spreads', 1),
(486, 'Mehadrin Nut Butters and Spreads', 1),
(487, 'Mehadrin Protein Bars', 1),
(488, 'Mehadrin Rice Cakes', 1),
(489, 'Mehadrin Salt Sugar and Sweeteners', 1),
(490, 'Mehadrin Dried Fruits', 1),
(491, 'Mehadrin Sports Drinks', 1),
(492, 'Mehadrin Sparkling Drinks', 1),
(493, 'Mehadrin Breakfast Pastries', 1),
(494, 'Mehadrin Savory Pastries', 1),
(495, 'Mehadrin Frozen Desserts', 1),
(496, 'Mehadrin Table Olives and Antipasti', 1),
(497, 'Mehadrin Gourmet Sauces', 1),
(498, 'Mehadrin Specialty Grains', 1),
(499, 'Mehadrin Ready Baking Products', 1),
(500, 'Mehadrin Healthy Snacks', 1);