insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (1, 'Osiek', 'Messerschmidt', 147, 'Jerusalem', 1);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (2, 'Kadukaung', 'Golf Course', 43, 'North', 2);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (3, 'Yuanshanzi', 'Meadow Vale', 200, 'North', 3);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (4, 'Ocaña', 'Emmet', 151, 'South', 4);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (5, 'Espanola', 'Superior', 5, 'Jerusalem', 5);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (6, 'Hatu Buh', 'Jenifer', 170, 'North', 6);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (7, 'Gamovo', 'Donald', 187, 'North', 7);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (8, 'Górki Wielkie', 'Warbler', 126, 'South', 8);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (9, 'Liliongan', 'Jackson', 54, 'South', 9);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (10, 'Yangyuan', 'Quincy', 181, 'Jerusalem', 10);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (11, 'Rathwire', 'Reinke', 14, 'South', 11);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (12, 'Chibuto', 'Northport', 182, 'North', 12);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (13, 'Qianxu Zhen', 'Eagan', 101, 'Jerusalem', 13);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (14, 'Santana', 'Ohio', 94, 'Jerusalem', 14);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (15, 'Shazi', 'Hollow Ridge', 144, 'Jerusalem', 15);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (16, 'Funaishikawa', 'Pennsylvania', 86, 'Center', 16);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (17, 'Barra Mansa', 'Donald', 18, 'Jerusalem', 17);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (18, 'Hadāli', 'Granby', 121, 'South', 18);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (19, 'Rudy', 'Pleasure', 117, 'South', 19);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (20, 'Nonggunong', 'Loomis', 36, 'Center', 20);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (21, 'Rennes', 'Stuart', 140, 'Center', 21);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (22, 'Tendō', 'Park Meadow', 60, 'Center', 22);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (23, 'Sapucaia', 'Lerdahl', 168, 'Center', 23);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (24, 'Embalse', 'Colorado', 58, 'North', 24);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (25, 'Chicoana', 'Cherokee', 12, 'Center', 25);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (26, 'La Francia', 'Loeprich', 56, 'South', 26);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (27, 'Macamic', 'Graedel', 78, 'Jerusalem', 27);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (28, 'K’olīto', 'Brickson Park', 73, 'Jerusalem', 28);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (29, 'Yacheng', 'Utah', 74, 'North', 29);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (30, 'Gondar', 'Farragut', 108, 'South', 30);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (31, 'Khanino', 'Bellgrove', 196, 'Jerusalem', 31);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (32, 'Cennan', 'Main', 7, 'North', 32);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (33, 'Gramaços', 'Burning Wood', 195, 'North', 33);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (34, 'Birigui', 'Stephen', 135, 'South', 34);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (35, 'Stettler', 'Riverside', 140, 'Jerusalem', 35);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (36, 'Murici', 'Clyde Gallagher', 11, 'South', 36);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (37, 'Xifengshan', 'Bay', 77, 'North', 37);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (38, 'Kelodan', 'Rowland', 187, 'North', 38);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (39, 'Blagaj', 'Judy', 25, 'Jerusalem', 39);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (40, 'Danyang', 'Dayton', 105, 'Jerusalem', 40);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (41, 'Bektemir', '1st', 31, 'South', 41);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (42, 'Bridel', '7th', 45, 'South', 42);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (43, 'Mata de São João', 'Ilene', 143, 'North', 43);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (44, 'Zemlyansk', 'Muir', 65, 'Center', 44);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (45, 'Bhamo', 'Orin', 46, 'North', 45);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (46, 'Pomacocha', 'Nevada', 17, 'Center', 46);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (47, 'Beaufort', 'Clemons', 155, 'Center', 47);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (48, 'Angers', 'Schlimgen', 21, 'Jerusalem', 48);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (49, 'Paso de Indios', 'Havey', 95, 'Center', 49);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (50, 'Xingfu', 'Gerald', 35, 'South', 50);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (51, 'Verkhniy Landekh', 'Erie', 178, 'Center', 51);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (52, 'Dalu', 'Summit', 19, 'Jerusalem', 52);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (53, 'Nanhu', 'Michigan', 188, 'North', 53);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (54, 'Virginia', 'Jenna', 71, 'North', 54);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (55, 'Álimos', 'Mcguire', 73, 'Jerusalem', 55);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (56, 'Cookshire-Eaton', 'Pankratz', 130, 'Jerusalem', 56);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (57, 'Risaralda', 'Manufacturers', 112, 'South', 57);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (58, 'Shuishiying', 'Meadow Vale', 114, 'South', 58);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (59, 'Marcos Juárez', 'La Follette', 91, 'North', 59);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (60, 'Baikui', 'Schurz', 165, 'Jerusalem', 60);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (61, 'Porkhov', 'Springs', 95, 'Center', 61);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (62, 'Bondowoso', 'Eastlawn', 63, 'Center', 62);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (63, 'Wanrongjiang', 'Luster', 55, 'Jerusalem', 63);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (64, 'Dalun', 'Ludington', 196, 'Jerusalem', 64);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (65, 'Zhigalovo', 'Moose', 122, 'South', 65);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (66, 'Itacurubí del Rosario', 'Bowman', 136, 'South', 66);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (67, 'Gornje Živinice', 'Pankratz', 77, 'South', 67);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (68, 'Huayuan', 'Knutson', 72, 'Jerusalem', 68);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (69, 'Jincang', 'Artisan', 165, 'North', 69);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (70, 'Dubova (Driloni)', 'Memorial', 39, 'North', 70);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (71, 'Armenokhórion', 'Morning', 120, 'South', 71);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (72, 'Åhus', 'Kipling', 111, 'Center', 72);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (73, 'Campo Verde', 'Red Cloud', 52, 'South', 73);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (74, 'Az̧ Z̧a‘āyin', 'Vermont', 64, 'Jerusalem', 74);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (75, 'Chiquinquirá', 'Division', 180, 'North', 75);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (76, 'Bagamoyo', 'Forest Run', 12, 'North', 76);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (77, 'Ipiales', 'Lien', 174, 'South', 77);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (78, 'Chalcos', 'Sommers', 191, 'North', 78);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (79, 'Magway', 'Talmadge', 160, 'Center', 79);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (80, 'Pengjia Zhaizi', 'Dwight', 38, 'Jerusalem', 80);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (81, 'Yuzui', 'Rowland', 26, 'North', 81);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (82, 'Pergan', 'Dryden', 63, 'Center', 82);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (83, 'Sitularang Landeuh', 'Warbler', 37, 'North', 83);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (84, 'Munkedal', 'Continental', 48, 'South', 84);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (85, 'Ping’an', 'South', 88, 'Jerusalem', 85);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (86, 'Suwangi Utara', 'North', 146, 'Jerusalem', 86);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (87, 'Tsapêraī', 'Harper', 195, 'Center', 87);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (88, 'Huayuan', 'Jenna', 49, 'North', 88);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (89, 'Babirik', 'Emmet', 76, 'South', 89);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (90, 'Obolensk', 'Lakewood', 22, 'Jerusalem', 90);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (91, 'La Jagua de Ibirico', 'Donald', 138, 'South', 91);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (92, 'Ostrówek', 'Hermina', 149, 'North', 92);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (93, 'Fonte da Vaca', 'Roxbury', 34, 'Center', 93);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (94, 'San Antonio', 'Dwight', 10, 'South', 94);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (95, 'Daja', 'Thompson', 34, 'South', 95);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (96, 'Depok', 'Petterle', 129, 'Jerusalem', 96);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (97, 'Asíni', 'Westerfield', 102, 'North', 97);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (98, 'Pingtan', 'Little Fleur', 197, 'North', 98);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (99, 'Banjar Yehsatang', 'Grover', 114, 'Center', 99);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (100, 'Assis', 'Emmet', 24, 'South', 100);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (101, 'Karakol', 'Fieldstone', 169, 'Jerusalem', 101);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (102, 'Sekampung', 'Larry', 61, 'Jerusalem', 102);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (103, 'Tulle', 'Continental', 144, 'Jerusalem', 103);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (104, 'Qiaotou', 'Anderson', 85, 'South', 104);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (105, 'Waenenda', 'Birchwood', 67, 'South', 105);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (106, 'Brwinów', 'Arkansas', 134, 'North', 106);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (107, 'Maraã', 'Scoville', 63, 'South', 107);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (108, 'Nîmes', 'Ridge Oak', 68, 'North', 108);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (109, 'Guadalupe', 'Michigan', 158, 'Jerusalem', 109);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (110, 'Ljungby', 'Bartelt', 182, 'Center', 110);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (111, 'Dabu', 'Dawn', 26, 'Jerusalem', 111);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (112, 'Shijie', 'Becker', 170, 'Center', 112);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (113, 'Tabasalu', 'Cottonwood', 58, 'Center', 113);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (114, 'Mpika', 'Clemons', 112, 'South', 114);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (115, 'Septfontaines', 'Twin Pines', 18, 'South', 115);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (116, 'Novyye Gorki', 'Erie', 51, 'North', 116);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (117, 'Geshan', 'Clove', 37, 'South', 117);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (118, 'Rozhniv', 'Lunder', 64, 'North', 118);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (119, 'Uluarang', 'Shelley', 110, 'Jerusalem', 119);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (120, 'Ayo', 'Glendale', 162, 'Center', 120);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (121, 'Baltimore', 'Monica', 112, 'Center', 121);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (122, 'Mbanza-Ngungu', 'Schmedeman', 161, 'Jerusalem', 122);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (123, 'Tougan', 'Ohio', 179, 'South', 123);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (124, 'Taiping', 'Main', 23, 'Center', 124);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (125, 'Saaban', 'Carioca', 119, 'North', 125);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (126, 'Julita', 'Hoffman', 151, 'South', 126);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (127, 'Guojia', 'Oneill', 148, 'South', 127);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (128, 'Ké-Macina', 'Ronald Regan', 155, 'Jerusalem', 128);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (129, 'Dno', 'Bluestem', 73, 'Jerusalem', 129);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (130, 'Baishi', 'Lunder', 168, 'Center', 130);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (131, 'Laocheng', 'Ramsey', 70, 'North', 131);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (132, 'Uusikaupunki', 'Stoughton', 152, 'Center', 132);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (133, 'Okrouhlice', 'Bluestem', 127, 'South', 133);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (134, 'Cambebba', 'Elmside', 192, 'South', 134);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (135, 'Sungai Raya', 'Thackeray', 59, 'South', 135);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (136, 'Kéfalos', 'Prairieview', 6, 'Jerusalem', 136);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (137, 'Fiorentino', 'Barnett', 84, 'South', 137);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (138, 'Muara', 'Merchant', 55, 'North', 138);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (139, 'Santa Teresita', 'Quincy', 111, 'North', 139);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (140, 'Jakartovice', 'Hanson', 84, 'Jerusalem', 140);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (141, 'Kanlagay', 'South', 106, 'Center', 141);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (142, 'Rybno', 'Lake View', 196, 'Jerusalem', 142);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (143, 'Kuantan', 'High Crossing', 7, 'Jerusalem', 143);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (144, 'Jelsa', 'Manufacturers', 121, 'Center', 144);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (145, 'Jiuxian', 'Dakota', 160, 'South', 145);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (146, 'Tuba', 'Carioca', 31, 'Center', 146);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (147, 'Jiangzao', 'Farwell', 91, 'South', 147);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (148, 'Skurup', 'Shasta', 67, 'Jerusalem', 148);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (149, 'Moville', 'Redwing', 25, 'South', 149);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (150, 'Xipi', 'David', 156, 'Jerusalem', 150);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (151, 'Tasīl', 'Blue Bill Park', 57, 'Center', 151);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (152, 'Numan', 'Hoffman', 11, 'South', 152);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (153, 'Montecristi', 'Arkansas', 21, 'Jerusalem', 153);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (154, 'Shuangjie', 'Cottonwood', 50, 'Jerusalem', 154);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (155, 'Alor Setar', 'Nancy', 72, 'Center', 155);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (156, 'Melfi', 'Nancy', 97, 'Jerusalem', 156);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (157, 'Bhairab Bāzār', 'Huxley', 170, 'Jerusalem', 157);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (158, 'Honkajoki', 'Mifflin', 105, 'Center', 158);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (159, 'Oenunu', 'Eggendart', 51, 'Center', 159);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (160, 'Lyon', 'Basil', 64, 'Center', 160);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (161, 'Taraban Timur', 'Farwell', 196, 'South', 161);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (162, 'Sere', 'Mayer', 10, 'Center', 162);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (163, 'Izumi', 'Welch', 47, 'Center', 163);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (164, 'Jajaway', 'Corry', 41, 'Center', 164);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (165, 'San Jose', 'Judy', 153, 'South', 165);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (166, 'Bhairāhawā', 'Lukken', 158, 'Center', 166);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (167, 'Montor Timur', 'Schiller', 43, 'Center', 167);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (168, 'Toulouse', 'Ohio', 152, 'Center', 168);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (169, 'Lukou', 'Oneill', 156, 'Jerusalem', 169);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (170, 'Qelëz', 'Macpherson', 8, 'Center', 170);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (171, 'Gilowice', 'Schurz', 185, 'Center', 171);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (172, 'Vypolzovo', 'La Follette', 152, 'Jerusalem', 172);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (173, 'Paicol', 'Daystar', 139, 'North', 173);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (174, 'Merke', 'Dennis', 157, 'Center', 174);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (175, 'Gizałki', 'Sloan', 100, 'Jerusalem', 175);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (176, 'Salfīt', 'Buell', 73, 'Center', 176);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (177, 'Sangalhos', 'Melvin', 166, 'North', 177);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (178, 'Tisma', 'Fulton', 173, 'Jerusalem', 178);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (179, 'Casma', 'Cascade', 50, 'Jerusalem', 179);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (180, 'Karajeun', 'Old Gate', 134, 'South', 180);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (181, 'Novouzensk', 'Paget', 93, 'Jerusalem', 181);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (182, 'Xiangshan', 'Thierer', 129, 'Jerusalem', 182);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (183, 'Ketian', 'Talisman', 105, 'North', 183);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (184, 'Pavlohrad', 'Homewood', 152, 'South', 184);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (185, 'Serra de Santa Marinha', 'Glendale', 194, 'South', 185);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (186, 'Urzhar', 'Sachtjen', 44, 'North', 186);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (187, 'Mardakyany', 'Pearson', 139, 'Center', 187);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (188, 'Tessaoua', 'Maryland', 44, 'Center', 188);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (189, 'Tongyuanpu', 'Village Green', 141, 'Center', 189);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (190, 'Dolgoprudnyy', 'Sommers', 58, 'South', 190);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (191, 'Ituverava', 'Westport', 81, 'Center', 191);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (192, 'Citeguh', '2nd', 190, 'Jerusalem', 192);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (193, 'Veiros', 'Springs', 14, 'Jerusalem', 193);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (194, 'Piltown', 'Evergreen', 93, 'North', 194);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (195, 'Bantul', 'Crest Line', 191, 'North', 195);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (196, 'Ryki', 'Mifflin', 63, 'South', 196);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (197, 'Ngaoundéré', 'Pepper Wood', 120, 'South', 197);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (198, 'Boussé', 'Bartelt', 137, 'South', 198);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (199, 'Vecumnieki', 'Dryden', 149, 'Jerusalem', 199);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (200, 'Néma', 'Arapahoe', 47, 'South', 200);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (201, 'Tsotsin-Yurt', 'Messerschmidt', 101, 'South', 201);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (202, 'Nangerang', 'Laurel', 128, 'Center', 202);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (203, 'Cusco', 'Service', 196, 'North', 203);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (204, 'Jabon', 'Fremont', 163, 'Jerusalem', 204);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (205, 'Brodnica', 'Nobel', 148, 'Center', 205);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (206, 'Oropesa', 'Vernon', 24, 'South', 206);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (207, 'Naikolan', 'Dixon', 45, 'Jerusalem', 207);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (208, 'Xiongbei', 'Pond', 103, 'North', 208);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (209, 'Cikajang', 'Cambridge', 152, 'South', 209);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (210, 'San Jacinto', 'Kedzie', 112, 'Jerusalem', 210);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (211, 'Yélimané', 'Valley Edge', 48, 'South', 211);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (212, 'Krasnokumskoye', '6th', 81, 'South', 212);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (213, 'Rokitno Szlacheckie', 'Novick', 12, 'Center', 213);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (214, 'Port Saint John’s', 'Eagan', 89, 'Center', 214);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (215, 'Granard', 'Grover', 48, 'North', 215);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (216, 'Açucena', 'Spohn', 29, 'North', 216);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (217, 'Bochum', 'Myrtle', 111, 'South', 217);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (218, 'Matsutō', 'Arrowood', 188, 'Center', 218);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (219, 'Tāngāil', 'Portage', 61, 'South', 219);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (220, 'Nunguan', 'Scott', 27, 'Jerusalem', 220);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (221, 'Wolongquan', 'Heffernan', 91, 'Center', 221);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (222, 'Badai', 'Almo', 157, 'Center', 222);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (223, 'Llocllapampa', 'Melody', 115, 'Center', 223);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (224, 'Nankāna Sāhib', 'Blaine', 139, 'Jerusalem', 224);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (225, 'Sarakhs', 'Helena', 28, 'South', 225);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (226, 'Zaporizhzhya', 'Magdeline', 187, 'North', 226);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (227, 'Ash Shuyūkh', 'Reinke', 137, 'South', 227);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (228, 'Detupia', 'Summerview', 118, 'Center', 228);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (229, 'Libacao', 'Calypso', 193, 'South', 229);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (230, 'Vasylkiv', 'Warrior', 47, 'Center', 230);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (231, 'Saparbay', 'Evergreen', 174, 'Center', 231);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (232, 'Qorveh', 'Lunder', 189, 'Center', 232);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (233, 'Ciela Lebak', 'Waywood', 89, 'Center', 233);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (234, 'Länsi-Turunmaa', 'Barby', 168, 'North', 234);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (235, 'Partenit', 'Summer Ridge', 92, 'South', 235);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (236, 'Monte Carmelo', 'Lakewood Gardens', 156, 'South', 236);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (237, 'Monastir', 'Bartelt', 188, 'South', 237);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (238, 'Dallas', 'Grayhawk', 163, 'Jerusalem', 238);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (239, 'Huaibei', 'Melrose', 41, 'Jerusalem', 239);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (240, 'Jicomé', 'Magdeline', 194, 'Center', 240);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (241, 'Pleiku', 'Arrowood', 103, 'South', 241);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (242, 'Langarūd', '7th', 20, 'Jerusalem', 242);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (243, 'Pines', 'Corscot', 27, 'Center', 243);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (244, 'Saint-Pierre', 'Randy', 183, 'Center', 244);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (245, 'San Sebastian', 'Pepper Wood', 138, 'Center', 245);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (246, 'Challhuahuacho', 'Arkansas', 130, 'South', 246);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (247, 'Bęczarka', 'Mallory', 73, 'Center', 247);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (248, 'Castlebellingham', 'Nobel', 89, 'North', 248);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (249, 'Derventa', 'Ilene', 75, 'South', 249);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (250, 'Asahikawa', 'Buell', 190, 'South', 250);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (251, 'Yarumal', 'Stoughton', 51, 'South', 251);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (252, 'Thị Trấn Quảng Uyên', 'Brown', 153, 'Center', 252);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (253, 'Karátoulas', 'Starling', 25, 'South', 253);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (254, 'Delod Pangkung', 'Eagle Crest', 17, 'South', 254);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (255, 'Arcos de Valdevez', 'Bowman', 127, 'South', 255);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (256, 'Angeghakot’', 'Armistice', 174, 'North', 256);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (257, 'Nanping', 'Laurel', 7, 'North', 257);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (258, 'Siderejo', 'Northview', 40, 'Jerusalem', 258);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (259, 'Cluny', 'Vidon', 46, 'North', 259);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (260, 'Bohou', 'Eggendart', 121, 'Center', 260);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (261, 'Guanshan', 'Corscot', 5, 'Jerusalem', 261);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (262, 'Tignoan', 'Green', 76, 'Center', 262);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (263, 'Yujiawu', 'Muir', 17, 'North', 263);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (264, 'Argir', 'Farmco', 76, 'Jerusalem', 264);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (265, 'Göteborg', 'Fordem', 153, 'Center', 265);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (266, 'Catac', 'Kedzie', 144, 'North', 266);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (267, 'Maranganí', 'Glendale', 111, 'Jerusalem', 267);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (268, 'København', 'Del Sol', 124, 'Center', 268);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (269, 'Großklein', 'Lakewood', 126, 'Center', 269);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (270, 'Cândido Mota', 'Fremont', 39, 'Jerusalem', 270);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (271, 'Baiyang', 'Carpenter', 116, 'North', 271);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (272, 'Detroit', 'Dwight', 41, 'Center', 272);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (273, 'Cikadu', 'Hanson', 90, 'Jerusalem', 273);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (274, 'Wuchagou', 'Atwood', 161, 'Center', 274);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (275, 'Wenlin', 'Anhalt', 60, 'South', 275);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (276, 'Saqqez', 'Gale', 15, 'North', 276);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (277, 'Bayamo', 'Heath', 52, 'Center', 277);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (278, 'Tugdan', 'Autumn Leaf', 110, 'Jerusalem', 278);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (279, 'Lueng Putu', 'Birchwood', 120, 'South', 279);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (280, 'Pak Thong Chai', 'Elgar', 94, 'Jerusalem', 280);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (281, 'Riversdale', 'Welch', 71, 'North', 281);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (282, 'Téra', 'Forest', 153, 'South', 282);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (283, 'Salvaleón de Higüey', 'Coolidge', 117, 'Jerusalem', 283);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (284, 'Wydminy', 'Riverside', 77, 'Center', 284);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (285, 'Dolní Dvořiště', 'Crowley', 110, 'North', 285);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (286, 'Abonnema', 'Delladonna', 18, 'Center', 286);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (287, 'Ylämaa', 'Dottie', 94, 'North', 287);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (288, 'Baculin', 'Dakota', 82, 'Center', 288);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (289, 'Alcoy', 'Norway Maple', 185, 'Center', 289);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (290, 'Bagou', 'Del Sol', 57, 'North', 290);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (291, '‘Arīqah', 'Vermont', 73, 'Jerusalem', 291);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (292, 'Tiberias', 'Shopko', 117, 'Jerusalem', 292);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (293, 'Wrząsowice', 'Petterle', 123, 'South', 293);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (294, 'Cernache do Bonjardim', 'Hagan', 134, 'Center', 294);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (295, 'Czerniewice', 'Golf', 96, 'Jerusalem', 295);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (296, 'Sumpur Kudus', 'Nevada', 20, 'Jerusalem', 296);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (297, 'Phoenix', 'Nobel', 8, 'Center', 297);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (298, 'Popova', 'Dahle', 151, 'Jerusalem', 298);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (299, 'Minggang', 'Donald', 16, 'Jerusalem', 299);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (300, 'Xingcheng', 'Veith', 143, 'Jerusalem', 300);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (301, 'Nularan', 'Oak', 124, 'South', 301);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (302, 'Taling Chan', 'Mockingbird', 146, 'Jerusalem', 302);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (303, 'Kilkenny', 'Pepper Wood', 75, 'South', 303);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (304, 'Popil''nya', 'Grasskamp', 39, 'Jerusalem', 304);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (305, 'Dongchen', 'Monument', 164, 'Center', 305);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (306, 'Redange-sur-Attert', 'Summer Ridge', 160, 'North', 306);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (307, 'Colca', 'Jackson', 127, 'Jerusalem', 307);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (308, 'Telsen', 'Bartelt', 98, 'Center', 308);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (309, 'San Juan', 'Burrows', 70, 'Center', 309);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (310, 'Aykhal', 'Lien', 58, 'North', 310);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (311, 'Camaligan', 'Almo', 140, 'Center', 311);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (312, 'Lushikeng', 'Crownhardt', 126, 'Jerusalem', 312);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (313, 'Purwosari', 'Crownhardt', 108, 'Jerusalem', 313);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (314, 'Wangjiachang', 'Fordem', 53, 'Jerusalem', 314);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (315, 'Zhen’an', 'Dapin', 137, 'Center', 315);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (316, 'Funtua', 'Knutson', 33, 'South', 316);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (317, 'Krajan Pocangan', 'Briar Crest', 91, 'Jerusalem', 317);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (318, 'Oni', 'Golf View', 177, 'North', 318);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (319, 'Blon’', 'Dwight', 60, 'South', 319);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (320, 'Bangker', 'Hollow Ridge', 60, 'Center', 320);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (321, 'Vestmannaeyjar', 'Paget', 71, 'Jerusalem', 321);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (322, 'Huangbizhuang', 'Jana', 3, 'South', 322);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (323, 'Antanhol', 'Green Ridge', 80, 'South', 323);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (324, 'Alikalia', 'Atwood', 196, 'Jerusalem', 324);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (325, 'Lubomierz', 'Heath', 18, 'Jerusalem', 325);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (326, 'Badung', 'Green Ridge', 19, 'Center', 326);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (327, 'Anju', 'Armistice', 116, 'South', 327);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (328, 'Jitian', 'Bashford', 43, 'Center', 328);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (329, 'Saint-Maurice-l''Exil', 'Ronald Regan', 93, 'Center', 329);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (330, 'Yuewan', 'Pond', 49, 'Jerusalem', 330);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (331, 'Tabug', 'Graedel', 10, 'South', 331);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (332, 'Hepingjie', 'Novick', 97, 'North', 332);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (333, 'Ituzaingó', '1st', 87, 'Jerusalem', 333);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (334, 'Ust’-Kut', 'Sauthoff', 73, 'Jerusalem', 334);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (335, 'Socorro', 'Sheridan', 2, 'South', 335);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (336, 'Draginje', 'Lukken', 103, 'South', 336);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (337, 'Tarrafal', 'Everett', 29, 'South', 337);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (338, 'Picoto', 'Clove', 75, 'North', 338);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (339, 'Dubréka', 'Clemons', 25, 'South', 339);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (340, 'Nizhniye Achaluki', 'Pepper Wood', 180, 'South', 340);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (341, 'El Viejo', 'Thierer', 128, 'South', 341);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (342, 'Opatów', 'Quincy', 19, 'Jerusalem', 342);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (343, 'Kulaman', 'Kropf', 10, 'South', 343);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (344, 'Budapest', 'Lunder', 31, 'Jerusalem', 344);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (345, 'Jiujie', 'Hansons', 43, 'South', 345);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (346, 'Kasina Wielka', 'Mccormick', 70, 'North', 346);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (347, 'Poggio di Chiesanuova', 'Hallows', 57, 'Jerusalem', 347);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (348, 'Oslo', 'Kim', 165, 'North', 348);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (349, 'Jingchuan', 'Golden Leaf', 98, 'Jerusalem', 349);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (350, 'Ganjiangtou', 'Valley Edge', 24, 'North', 350);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (351, 'Nunmanu', 'Talisman', 98, 'Center', 351);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (352, 'Itu', 'Ryan', 12, 'Jerusalem', 352);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (353, 'Jugezhuang', 'Dawn', 112, 'Jerusalem', 353);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (354, 'Étampes', 'Luster', 155, 'Center', 354);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (355, 'Napier', 'Mallard', 150, 'Jerusalem', 355);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (356, 'Kalá Déndra', 'Vahlen', 168, 'Jerusalem', 356);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (357, 'Pasrukrajan Satu', 'Mesta', 53, 'Jerusalem', 357);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (358, 'Loreto', 'Michigan', 166, 'South', 358);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (359, 'Bay Roberts', 'Monica', 35, 'Jerusalem', 359);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (360, 'Ciheras', 'Stang', 158, 'North', 360);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (361, 'T’azagyugh', 'Jana', 198, 'Jerusalem', 361);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (362, 'Thul', 'Hanover', 101, 'North', 362);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (363, 'Conceição da Feira', 'Oneill', 139, 'Jerusalem', 363);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (364, 'Landskrona', 'Michigan', 11, 'Center', 364);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (365, 'Dallas', 'Northridge', 85, 'South', 365);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (366, 'Yilongyong', 'Starling', 85, 'South', 366);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (367, 'Yeosu', 'Tennyson', 41, 'South', 367);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (368, 'Dukhovshchina', 'Jenna', 171, 'Center', 368);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (369, 'Anao', 'Hooker', 166, 'Jerusalem', 369);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (370, 'Luodian', 'Grasskamp', 197, 'Jerusalem', 370);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (371, 'Marigot', 'Macpherson', 9, 'Center', 371);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (372, 'Keli', 'Grayhawk', 15, 'Jerusalem', 372);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (373, 'Stare Miasto', 'Autumn Leaf', 37, 'South', 373);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (374, 'Marcara', 'Carey', 37, 'South', 374);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (375, 'Wu’an', 'Shoshone', 173, 'Center', 375);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (376, 'Três Lagoas', 'Towne', 180, 'Jerusalem', 376);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (377, 'Daban', 'Grover', 126, 'North', 377);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (378, 'Lazurne', 'Onsgard', 167, 'North', 378);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (379, 'Wien', 'Lake View', 156, 'North', 379);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (380, 'Xinó Neró', 'Michigan', 187, 'South', 380);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (381, 'Hidalgo', 'Holmberg', 105, 'Jerusalem', 381);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (382, 'Badou', 'Veith', 136, 'North', 382);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (383, 'Loikaw', 'Pennsylvania', 59, 'South', 383);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (384, 'Adirejo', 'Melvin', 57, 'South', 384);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (385, 'Taber', 'Claremont', 9, 'South', 385);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (386, 'Tokoname', 'Corscot', 96, 'South', 386);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (387, 'Kuala Lumpur', 'Comanche', 114, 'South', 387);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (388, 'Millau', 'Briar Crest', 118, 'North', 388);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (389, 'Kepel', 'Lyons', 192, 'South', 389);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (390, 'Yonglong', 'Butternut', 106, 'South', 390);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (391, 'Oro Verde', 'Warbler', 182, 'North', 391);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (392, 'Cemara', 'Superior', 134, 'Jerusalem', 392);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (393, 'Zaranj', 'Bobwhite', 78, 'North', 393);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (394, 'Berezovo', 'Bluestem', 176, 'South', 394);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (395, 'Mursaba', 'Grayhawk', 28, 'Jerusalem', 395);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (396, 'Masākin', 'Chinook', 112, 'Center', 396);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (397, 'Barrosas', 'Novick', 153, 'Center', 397);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (398, 'Lachowice', 'Red Cloud', 140, 'Center', 398);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (399, 'Butembo', 'Brickson Park', 156, 'Jerusalem', 399);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (400, 'Želetava', 'Lyons', 167, 'Jerusalem', 400);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (401, 'Perzów', 'Ridge Oak', 21, 'South', 401);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (402, 'Cocieri', 'Summit', 29, 'South', 402);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (403, 'Vera', 'Di Loreto', 22, 'South', 403);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (404, 'Bayt ‘Anān', 'Wayridge', 23, 'Center', 404);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (405, 'Sōja', 'Coolidge', 169, 'Jerusalem', 405);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (406, 'Gränna', 'Melody', 137, 'South', 406);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (407, 'Chaeryŏng-ŭp', 'Sage', 124, 'Jerusalem', 407);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (408, 'Nueva Imperial', 'American', 108, 'South', 408);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (409, 'Heping', 'Wayridge', 114, 'Jerusalem', 409);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (410, 'Tafeng', 'Darwin', 26, 'Jerusalem', 410);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (411, 'Hamilton', 'Fuller', 8, 'North', 411);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (412, 'Zhujiachang', 'Sherman', 113, 'North', 412);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (413, 'Karítsa', 'Spenser', 22, 'North', 413);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (414, 'Bogorame', 'Arapahoe', 122, 'Jerusalem', 414);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (415, 'Lalig', 'Upham', 103, 'North', 415);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (416, 'Gobernador Ingeniero Valentín Virasoro', 'Granby', 148, 'Jerusalem', 416);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (417, 'Gamagōri', 'Warrior', 60, 'North', 417);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (418, 'Cruz das Almas', 'Nobel', 106, 'Center', 418);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (419, 'Tobi Village', 'Algoma', 20, 'Jerusalem', 419);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (420, 'Zhuoshui', 'Pennsylvania', 145, 'Center', 420);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (421, 'Doumen', 'Southridge', 165, 'Center', 421);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (422, 'Yulin', 'Barby', 45, 'North', 422);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (423, 'Plužine', 'Pierstorff', 123, 'South', 423);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (424, 'Mata', 'Nevada', 1, 'North', 424);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (425, 'Mets Parni', 'Bartelt', 100, 'Center', 425);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (426, 'Harstad', 'Corben', 20, 'South', 426);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (427, 'Socos', 'Dawn', 22, 'Center', 427);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (428, 'Ruyigi', 'Anthes', 6, 'Center', 428);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (429, 'Dukla', 'American Ash', 172, 'South', 429);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (430, 'Baima', 'Rusk', 85, 'Center', 430);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (431, 'Merklín', 'Sundown', 193, 'Jerusalem', 431);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (432, 'Sundbyberg', 'Saint Paul', 162, 'Center', 432);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (433, 'Lazaro Cardenas', 'Mayfield', 100, 'South', 433);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (434, 'Bintulu', 'Memorial', 94, 'North', 434);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (435, 'Castres', 'Butterfield', 144, 'Center', 435);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (436, 'Rivera', 'Manley', 189, 'South', 436);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (437, 'München', 'Kropf', 82, 'Jerusalem', 437);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (438, 'Fāraskūr', 'School', 85, 'Center', 438);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (439, 'Xingyuan', 'Derek', 48, 'North', 439);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (440, 'Malitubog', '1st', 29, 'Jerusalem', 440);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (441, 'Muikamachi', 'Clemons', 47, 'North', 441);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (442, 'Kopang Satu', 'Claremont', 101, 'Jerusalem', 442);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (443, 'Messejana', 'Charing Cross', 179, 'South', 443);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (444, 'Criação Velha', 'La Follette', 171, 'North', 444);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (445, 'Ning’an', 'Oak Valley', 78, 'Jerusalem', 445);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (446, 'Chinhoyi', 'Fuller', 149, 'Jerusalem', 446);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (447, 'Changzhi', 'Laurel', 68, 'Jerusalem', 447);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (448, 'Chesapeake', 'Nelson', 51, 'North', 448);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (449, 'Padamulya', 'Chinook', 157, 'Jerusalem', 449);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (450, 'Prosperidad', 'Hoard', 186, 'North', 450);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (451, 'Tocok', 'Porter', 144, 'North', 451);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (452, 'Rancapare', 'Ilene', 105, 'North', 452);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (453, 'Drakhtik', 'Heath', 119, 'Jerusalem', 453);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (454, 'Changtan', 'Maywood', 13, 'Center', 454);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (455, 'Katsina-Ala', 'Bunker Hill', 178, 'Center', 455);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (456, 'Ariana', 'Old Shore', 1, 'North', 456);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (457, 'Granica', 'Cottonwood', 165, 'South', 457);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (458, 'Saint-Julien-en-Genevois', 'Melody', 16, 'South', 458);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (459, 'Lawa-an', 'Birchwood', 42, 'North', 459);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (460, 'Kolmården', 'Starling', 4, 'South', 460);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (461, 'Divača', 'Melrose', 71, 'South', 461);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (462, 'Caijiang', 'Prairie Rose', 112, 'Center', 462);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (463, 'Xiaoyue', 'Cottonwood', 96, 'South', 463);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (464, 'Aksarka', 'Loftsgordon', 18, 'South', 464);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (465, 'Coris', 'Trailsway', 41, 'South', 465);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (466, 'Pedra Azul', 'Russell', 160, 'Center', 466);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (467, 'Cirangrang', 'Bobwhite', 114, 'North', 467);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (468, 'Xiangdong', 'Grasskamp', 33, 'South', 468);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (469, 'Welisara', 'Transport', 122, 'Center', 469);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (470, 'Mae Chan', 'Dakota', 75, 'North', 470);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (471, 'Bendorubuh', '7th', 40, 'Jerusalem', 471);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (472, 'Farroupilha', 'Fairview', 89, 'South', 472);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (473, 'Yovon', 'Center', 12, 'South', 473);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (474, 'Janas', 'Dixon', 188, 'North', 474);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (475, 'Shanghu', 'Wayridge', 30, 'Center', 475);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (476, 'Letlhakane', 'Emmet', 133, 'Center', 476);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (477, 'Talas', 'Farragut', 146, 'Jerusalem', 477);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (478, 'Tangwu', 'Dovetail', 170, 'Jerusalem', 478);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (479, 'Yukuhashi', '3rd', 85, 'Center', 479);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (480, 'Storuman', 'Duke', 194, 'Center', 480);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (481, 'Vyatskiye Polyany', 'Kim', 89, 'Center', 481);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (482, 'Máncora', 'Shelley', 82, 'Jerusalem', 482);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (483, 'Budapest', 'Bellgrove', 55, 'Center', 483);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (484, 'Mingcheng', 'Sutteridge', 44, 'North', 484);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (485, 'Mechrá Belqsiri', 'Hoard', 122, 'South', 485);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (486, 'Ōfunato', 'Hoffman', 40, 'South', 486);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (487, 'Haitang', 'Vernon', 58, 'Center', 487);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (488, 'Phrae', 'Green', 110, 'Center', 488);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (489, 'Xinzhou', 'Ridgeview', 133, 'North', 489);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (490, 'Emin', 'Pond', 190, 'Jerusalem', 490);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (491, 'Pittsburgh', 'Lakewood', 117, 'Jerusalem', 491);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (492, 'Tékane', 'Continental', 51, 'Jerusalem', 492);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (493, 'Machikou', 'Hudson', 6, 'Jerusalem', 493);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (494, 'Itinga', 'Thompson', 106, 'South', 494);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (495, 'Bria', 'Independence', 77, 'North', 495);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (496, 'Wonosari', 'Monica', 62, 'North', 496);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (497, 'Néa Ionía', 'Homewood', 2, 'South', 497);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (498, 'Corozal', 'Summer Ridge', 174, 'North', 498);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (499, 'Nikol’skoye', 'Mccormick', 37, 'Center', 499);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (500, 'Pataha', 'Washington', 139, 'South', 500);
