insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (1, 'Tel Aviv', 'Ben Yehuda Street', 102, 'North', 1);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (2, 'Jerusalem', 'Dizengoff Street', 42, 'Center', 2);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (3, 'Haifa', 'Rothschild Boulevard', 75, 'West', 3);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (4, 'Rishon LeZion', 'Allenby Street', 116, 'West', 4);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (5, 'Petah Tikva', 'King George Street', 173, 'South', 5);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (6, 'Ashdod', 'HaCarmel Market', 55, 'South', 6);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (7, 'Netanya', 'Nahalat Binyamin Street', 136, 'East', 7);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (8, 'Beer Sheva', 'Herzl Street', 133, 'North', 8);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (9, 'Holon', 'Sderot Rothschild', 176, 'West', 9);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (10, 'Bnei Brak', 'Yehuda Halevi Street', 148, 'South', 10);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (11, 'Rehovot', 'Ibn Gabirol Street', 117, 'East', 11);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (12, 'Ashkelon', 'Shenkin Street', 23, 'West', 12);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (13, 'Bat Yam', 'Emek Refaim Street', 97, 'West', 13);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (14, 'Herzliya', 'Jaffa Street', 11, 'East', 14);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (15, 'Kfar Saba', 'Beit Lehem Road', 66, 'East', 15);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (16, 'Hadera', 'Ben Yehuda Street', 98, 'West', 16);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (17, 'Modiin', 'Dizengoff Street', 13, 'North', 17);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (18, 'Nazareth', 'Rothschild Boulevard', 17, 'East', 18);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (19, 'Lod', 'Allenby Street', 126, 'West', 19);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (20, 'Ramla', 'King George Street', 189, 'East', 20);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (21, 'Afula', 'HaCarmel Market', 21, 'Center', 21);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (22, 'Eilat', 'Nahalat Binyamin Street', 100, 'South', 22);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (23, 'Tiberias', 'Herzl Street', 113, 'South', 23);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (24, 'Kiryat Gat', 'Sderot Rothschild', 76, 'South', 24);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (25, 'Yavne', 'Yehuda Halevi Street', 143, 'Center', 25);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (26, 'Nahariya', 'Ibn Gabirol Street', 130, 'South', 26);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (27, 'Raanana', 'Shenkin Street', 63, 'Center', 27);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (28, 'Givatayim', 'Emek Refaim Street', 114, 'North', 28);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (29, 'Kiryat Ono', 'Jaffa Street', 131, 'North', 29);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (30, 'Rosh HaAyin', 'Beit Lehem Road', 141, 'East', 30);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (31, 'Yokneam', 'Ben Yehuda Street', 114, 'East', 31);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (32, 'Zichron Yaakov', 'Dizengoff Street', 135, 'South', 32);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (33, 'Caesarea', 'Rothschild Boulevard', 57, 'East', 33);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (34, 'Pardes Hanna', 'Allenby Street', 36, 'North', 34);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (35, 'Or Akiva', 'King George Street', 27, 'South', 35);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (36, 'Karmiel', 'HaCarmel Market', 138, 'East', 36);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (37, 'Safed', 'Nahalat Binyamin Street', 136, 'East', 37);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (38, 'Migdal HaEmek', 'Herzl Street', 167, 'Center', 38);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (39, 'Nof HaGalil', 'Sderot Rothschild', 145, 'East', 39);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (40, 'Kiryat Shmona', 'Yehuda Halevi Street', 73, 'North', 40);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (41, 'Dimona', 'Ibn Gabirol Street', 131, 'South', 41);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (42, 'Arad', 'Shenkin Street', 108, 'North', 42);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (43, 'Mevaseret Zion', 'Emek Refaim Street', 2, 'South', 43);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (44, 'Maale Adumim', 'Jaffa Street', 195, 'South', 44);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (45, 'Beit Shemesh', 'Beit Lehem Road', 179, 'North', 45);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (46, 'Nes Ziona', 'Ben Yehuda Street', 146, 'South', 46);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (47, 'Shoham', 'Dizengoff Street', 128, 'North', 47);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (48, 'Gedera', 'Rothschild Boulevard', 103, 'South', 48);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (49, 'Gan Yavne', 'Allenby Street', 48, 'South', 49);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (50, 'Kiryat Malakhi', 'King George Street', 123, 'West', 50);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (51, 'Tel Aviv', 'HaCarmel Market', 110, 'South', 51);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (52, 'Jerusalem', 'Nahalat Binyamin Street', 194, 'East', 52);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (53, 'Haifa', 'Herzl Street', 100, 'North', 53);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (54, 'Rishon LeZion', 'Sderot Rothschild', 79, 'East', 54);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (55, 'Petah Tikva', 'Yehuda Halevi Street', 89, 'South', 55);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (56, 'Ashdod', 'Ibn Gabirol Street', 94, 'South', 56);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (57, 'Netanya', 'Shenkin Street', 131, 'North', 57);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (58, 'Beer Sheva', 'Emek Refaim Street', 125, 'Center', 58);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (59, 'Holon', 'Jaffa Street', 54, 'West', 59);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (60, 'Bnei Brak', 'Beit Lehem Road', 66, 'South', 60);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (61, 'Rehovot', 'Ben Yehuda Street', 158, 'Center', 61);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (62, 'Ashkelon', 'Dizengoff Street', 125, 'Center', 62);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (63, 'Bat Yam', 'Rothschild Boulevard', 89, 'South', 63);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (64, 'Herzliya', 'Allenby Street', 51, 'South', 64);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (65, 'Kfar Saba', 'King George Street', 100, 'Center', 65);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (66, 'Hadera', 'HaCarmel Market', 192, 'Center', 66);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (67, 'Modiin', 'Nahalat Binyamin Street', 178, 'Center', 67);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (68, 'Nazareth', 'Herzl Street', 116, 'North', 68);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (69, 'Lod', 'Sderot Rothschild', 171, 'South', 69);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (70, 'Ramla', 'Yehuda Halevi Street', 196, 'South', 70);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (71, 'Afula', 'Ibn Gabirol Street', 107, 'East', 71);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (72, 'Eilat', 'Shenkin Street', 58, 'Center', 72);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (73, 'Tiberias', 'Emek Refaim Street', 65, 'East', 73);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (74, 'Kiryat Gat', 'Jaffa Street', 77, 'Center', 74);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (75, 'Yavne', 'Beit Lehem Road', 51, 'Center', 75);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (76, 'Nahariya', 'Ben Yehuda Street', 33, 'South', 76);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (77, 'Raanana', 'Dizengoff Street', 123, 'West', 77);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (78, 'Givatayim', 'Rothschild Boulevard', 104, 'Center', 78);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (79, 'Kiryat Ono', 'Allenby Street', 147, 'East', 79);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (80, 'Rosh HaAyin', 'King George Street', 67, 'West', 80);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (81, 'Yokneam', 'HaCarmel Market', 165, 'South', 81);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (82, 'Zichron Yaakov', 'Nahalat Binyamin Street', 163, 'East', 82);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (83, 'Caesarea', 'Herzl Street', 109, 'East', 83);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (84, 'Pardes Hanna', 'Sderot Rothschild', 119, 'North', 84);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (85, 'Or Akiva', 'Yehuda Halevi Street', 7, 'Center', 85);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (86, 'Karmiel', 'Ibn Gabirol Street', 16, 'North', 86);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (87, 'Safed', 'Shenkin Street', 28, 'West', 87);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (88, 'Migdal HaEmek', 'Emek Refaim Street', 173, 'East', 88);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (89, 'Nof HaGalil', 'Jaffa Street', 176, 'East', 89);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (90, 'Kiryat Shmona', 'Beit Lehem Road', 156, 'North', 90);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (91, 'Dimona', 'Ben Yehuda Street', 191, 'Center', 91);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (92, 'Arad', 'Dizengoff Street', 68, 'Center', 92);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (93, 'Mevaseret Zion', 'Rothschild Boulevard', 51, 'East', 93);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (94, 'Maale Adumim', 'Allenby Street', 24, 'Center', 94);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (95, 'Beit Shemesh', 'King George Street', 132, 'Center', 95);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (96, 'Nes Ziona', 'HaCarmel Market', 93, 'South', 96);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (97, 'Shoham', 'Nahalat Binyamin Street', 91, 'South', 97);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (98, 'Gedera', 'Herzl Street', 31, 'East', 98);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (99, 'Gan Yavne', 'Sderot Rothschild', 79, 'South', 99);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (100, 'Kiryat Malakhi', 'Yehuda Halevi Street', 36, 'East', 100);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (101, 'Tel Aviv', 'Ibn Gabirol Street', 57, 'West', 101);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (102, 'Jerusalem', 'Shenkin Street', 88, 'South', 102);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (103, 'Haifa', 'Emek Refaim Street', 170, 'North', 103);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (104, 'Rishon LeZion', 'Jaffa Street', 70, 'South', 104);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (105, 'Petah Tikva', 'Beit Lehem Road', 71, 'West', 105);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (106, 'Ashdod', 'Ben Yehuda Street', 182, 'Center', 106);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (107, 'Netanya', 'Dizengoff Street', 84, 'Center', 107);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (108, 'Beer Sheva', 'Rothschild Boulevard', 57, 'Center', 108);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (109, 'Holon', 'Allenby Street', 97, 'North', 109);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (110, 'Bnei Brak', 'King George Street', 39, 'West', 110);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (111, 'Rehovot', 'HaCarmel Market', 127, 'North', 111);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (112, 'Ashkelon', 'Nahalat Binyamin Street', 130, 'North', 112);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (113, 'Bat Yam', 'Herzl Street', 80, 'West', 113);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (114, 'Herzliya', 'Sderot Rothschild', 110, 'Center', 114);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (115, 'Kfar Saba', 'Yehuda Halevi Street', 52, 'East', 115);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (116, 'Hadera', 'Ibn Gabirol Street', 39, 'South', 116);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (117, 'Modiin', 'Shenkin Street', 18, 'North', 117);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (118, 'Nazareth', 'Emek Refaim Street', 173, 'South', 118);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (119, 'Lod', 'Jaffa Street', 135, 'East', 119);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (120, 'Ramla', 'Beit Lehem Road', 155, 'South', 120);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (121, 'Afula', 'Ben Yehuda Street', 135, 'West', 121);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (122, 'Eilat', 'Dizengoff Street', 91, 'South', 122);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (123, 'Tiberias', 'Rothschild Boulevard', 5, 'North', 123);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (124, 'Kiryat Gat', 'Allenby Street', 142, 'Center', 124);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (125, 'Yavne', 'King George Street', 194, 'North', 125);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (126, 'Nahariya', 'HaCarmel Market', 62, 'West', 126);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (127, 'Raanana', 'Nahalat Binyamin Street', 25, 'East', 127);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (128, 'Givatayim', 'Herzl Street', 30, 'West', 128);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (129, 'Kiryat Ono', 'Sderot Rothschild', 160, 'South', 129);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (130, 'Rosh HaAyin', 'Yehuda Halevi Street', 146, 'South', 130);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (131, 'Yokneam', 'Ibn Gabirol Street', 86, 'Center', 131);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (132, 'Zichron Yaakov', 'Shenkin Street', 143, 'South', 132);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (133, 'Caesarea', 'Emek Refaim Street', 164, 'North', 133);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (134, 'Pardes Hanna', 'Jaffa Street', 83, 'South', 134);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (135, 'Or Akiva', 'Beit Lehem Road', 13, 'West', 135);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (136, 'Karmiel', 'Ben Yehuda Street', 173, 'East', 136);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (137, 'Safed', 'Dizengoff Street', 156, 'West', 137);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (138, 'Migdal HaEmek', 'Rothschild Boulevard', 134, 'North', 138);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (139, 'Nof HaGalil', 'Allenby Street', 162, 'Center', 139);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (140, 'Kiryat Shmona', 'King George Street', 70, 'South', 140);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (141, 'Dimona', 'HaCarmel Market', 146, 'Center', 141);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (142, 'Arad', 'Nahalat Binyamin Street', 3, 'North', 142);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (143, 'Mevaseret Zion', 'Herzl Street', 43, 'East', 143);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (144, 'Maale Adumim', 'Sderot Rothschild', 139, 'South', 144);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (145, 'Beit Shemesh', 'Yehuda Halevi Street', 183, 'Center', 145);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (146, 'Nes Ziona', 'Ibn Gabirol Street', 9, 'West', 146);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (147, 'Shoham', 'Shenkin Street', 166, 'Center', 147);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (148, 'Gedera', 'Emek Refaim Street', 45, 'West', 148);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (149, 'Gan Yavne', 'Jaffa Street', 131, 'Center', 149);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (150, 'Kiryat Malakhi', 'Beit Lehem Road', 17, 'South', 150);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (151, 'Tel Aviv', 'Ben Yehuda Street', 165, 'North', 151);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (152, 'Jerusalem', 'Dizengoff Street', 166, 'East', 152);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (153, 'Haifa', 'Rothschild Boulevard', 36, 'East', 153);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (154, 'Rishon LeZion', 'Allenby Street', 164, 'Center', 154);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (155, 'Petah Tikva', 'King George Street', 28, 'West', 155);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (156, 'Ashdod', 'HaCarmel Market', 151, 'North', 156);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (157, 'Netanya', 'Nahalat Binyamin Street', 73, 'North', 157);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (158, 'Beer Sheva', 'Herzl Street', 100, 'North', 158);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (159, 'Holon', 'Sderot Rothschild', 52, 'South', 159);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (160, 'Bnei Brak', 'Yehuda Halevi Street', 98, 'East', 160);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (161, 'Rehovot', 'Ibn Gabirol Street', 129, 'South', 161);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (162, 'Ashkelon', 'Shenkin Street', 151, 'North', 162);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (163, 'Bat Yam', 'Emek Refaim Street', 156, 'North', 163);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (164, 'Herzliya', 'Jaffa Street', 179, 'North', 164);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (165, 'Kfar Saba', 'Beit Lehem Road', 182, 'Center', 165);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (166, 'Hadera', 'Ben Yehuda Street', 39, 'West', 166);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (167, 'Modiin', 'Dizengoff Street', 41, 'East', 167);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (168, 'Nazareth', 'Rothschild Boulevard', 6, 'East', 168);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (169, 'Lod', 'Allenby Street', 100, 'South', 169);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (170, 'Ramla', 'King George Street', 66, 'West', 170);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (171, 'Afula', 'HaCarmel Market', 27, 'East', 171);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (172, 'Eilat', 'Nahalat Binyamin Street', 104, 'South', 172);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (173, 'Tiberias', 'Herzl Street', 193, 'North', 173);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (174, 'Kiryat Gat', 'Sderot Rothschild', 184, 'North', 174);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (175, 'Yavne', 'Yehuda Halevi Street', 169, 'South', 175);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (176, 'Nahariya', 'Ibn Gabirol Street', 87, 'North', 176);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (177, 'Raanana', 'Shenkin Street', 158, 'West', 177);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (178, 'Givatayim', 'Emek Refaim Street', 153, 'North', 178);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (179, 'Kiryat Ono', 'Jaffa Street', 148, 'West', 179);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (180, 'Rosh HaAyin', 'Beit Lehem Road', 187, 'East', 180);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (181, 'Yokneam', 'Ben Yehuda Street', 133, 'East', 181);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (182, 'Zichron Yaakov', 'Dizengoff Street', 65, 'East', 182);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (183, 'Caesarea', 'Rothschild Boulevard', 172, 'Center', 183);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (184, 'Pardes Hanna', 'Allenby Street', 8, 'North', 184);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (185, 'Or Akiva', 'King George Street', 188, 'West', 185);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (186, 'Karmiel', 'HaCarmel Market', 76, 'West', 186);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (187, 'Safed', 'Nahalat Binyamin Street', 5, 'Center', 187);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (188, 'Migdal HaEmek', 'Herzl Street', 68, 'North', 188);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (189, 'Nof HaGalil', 'Sderot Rothschild', 68, 'Center', 189);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (190, 'Kiryat Shmona', 'Yehuda Halevi Street', 13, 'Center', 190);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (191, 'Dimona', 'Ibn Gabirol Street', 37, 'East', 191);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (192, 'Arad', 'Shenkin Street', 24, 'Center', 192);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (193, 'Mevaseret Zion', 'Emek Refaim Street', 34, 'Center', 193);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (194, 'Maale Adumim', 'Jaffa Street', 19, 'South', 194);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (195, 'Beit Shemesh', 'Beit Lehem Road', 139, 'West', 195);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (196, 'Nes Ziona', 'Ben Yehuda Street', 13, 'West', 196);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (197, 'Shoham', 'Dizengoff Street', 142, 'North', 197);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (198, 'Gedera', 'Rothschild Boulevard', 91, 'Center', 198);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (199, 'Gan Yavne', 'Allenby Street', 3, 'South', 199);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (200, 'Kiryat Malakhi', 'King George Street', 140, 'West', 200);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (201, 'Tel Aviv', 'HaCarmel Market', 62, 'West', 201);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (202, 'Jerusalem', 'Nahalat Binyamin Street', 187, 'South', 202);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (203, 'Haifa', 'Herzl Street', 51, 'East', 203);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (204, 'Rishon LeZion', 'Sderot Rothschild', 175, 'West', 204);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (205, 'Petah Tikva', 'Yehuda Halevi Street', 48, 'East', 205);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (206, 'Ashdod', 'Ibn Gabirol Street', 42, 'East', 206);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (207, 'Netanya', 'Shenkin Street', 111, 'Center', 207);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (208, 'Beer Sheva', 'Emek Refaim Street', 123, 'Center', 208);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (209, 'Holon', 'Jaffa Street', 180, 'West', 209);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (210, 'Bnei Brak', 'Beit Lehem Road', 126, 'South', 210);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (211, 'Rehovot', 'Ben Yehuda Street', 183, 'East', 211);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (212, 'Ashkelon', 'Dizengoff Street', 136, 'East', 212);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (213, 'Bat Yam', 'Rothschild Boulevard', 153, 'Center', 213);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (214, 'Herzliya', 'Allenby Street', 54, 'East', 214);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (215, 'Kfar Saba', 'King George Street', 121, 'West', 215);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (216, 'Hadera', 'HaCarmel Market', 18, 'Center', 216);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (217, 'Modiin', 'Nahalat Binyamin Street', 121, 'East', 217);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (218, 'Nazareth', 'Herzl Street', 3, 'North', 218);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (219, 'Lod', 'Sderot Rothschild', 19, 'Center', 219);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (220, 'Ramla', 'Yehuda Halevi Street', 109, 'North', 220);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (221, 'Afula', 'Ibn Gabirol Street', 125, 'Center', 221);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (222, 'Eilat', 'Shenkin Street', 103, 'West', 222);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (223, 'Tiberias', 'Emek Refaim Street', 125, 'South', 223);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (224, 'Kiryat Gat', 'Jaffa Street', 75, 'North', 224);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (225, 'Yavne', 'Beit Lehem Road', 179, 'South', 225);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (226, 'Nahariya', 'Ben Yehuda Street', 97, 'North', 226);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (227, 'Raanana', 'Dizengoff Street', 4, 'Center', 227);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (228, 'Givatayim', 'Rothschild Boulevard', 14, 'Center', 228);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (229, 'Kiryat Ono', 'Allenby Street', 49, 'East', 229);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (230, 'Rosh HaAyin', 'King George Street', 122, 'East', 230);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (231, 'Yokneam', 'HaCarmel Market', 122, 'North', 231);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (232, 'Zichron Yaakov', 'Nahalat Binyamin Street', 157, 'North', 232);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (233, 'Caesarea', 'Herzl Street', 30, 'Center', 233);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (234, 'Pardes Hanna', 'Sderot Rothschild', 175, 'North', 234);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (235, 'Or Akiva', 'Yehuda Halevi Street', 77, 'North', 235);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (236, 'Karmiel', 'Ibn Gabirol Street', 166, 'West', 236);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (237, 'Safed', 'Shenkin Street', 138, 'East', 237);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (238, 'Migdal HaEmek', 'Emek Refaim Street', 154, 'West', 238);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (239, 'Nof HaGalil', 'Jaffa Street', 26, 'North', 239);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (240, 'Kiryat Shmona', 'Beit Lehem Road', 48, 'South', 240);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (241, 'Dimona', 'Ben Yehuda Street', 156, 'East', 241);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (242, 'Arad', 'Dizengoff Street', 13, 'Center', 242);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (243, 'Mevaseret Zion', 'Rothschild Boulevard', 138, 'Center', 243);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (244, 'Maale Adumim', 'Allenby Street', 132, 'North', 244);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (245, 'Beit Shemesh', 'King George Street', 169, 'South', 245);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (246, 'Nes Ziona', 'HaCarmel Market', 188, 'South', 246);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (247, 'Shoham', 'Nahalat Binyamin Street', 159, 'East', 247);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (248, 'Gedera', 'Herzl Street', 3, 'West', 248);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (249, 'Gan Yavne', 'Sderot Rothschild', 12, 'Center', 249);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (250, 'Kiryat Malakhi', 'Yehuda Halevi Street', 153, 'West', 250);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (251, 'Tel Aviv', 'Ibn Gabirol Street', 84, 'East', 251);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (252, 'Jerusalem', 'Shenkin Street', 195, 'South', 252);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (253, 'Haifa', 'Emek Refaim Street', 194, 'North', 253);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (254, 'Rishon LeZion', 'Jaffa Street', 128, 'West', 254);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (255, 'Petah Tikva', 'Beit Lehem Road', 87, 'West', 255);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (256, 'Ashdod', 'Ben Yehuda Street', 83, 'East', 256);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (257, 'Netanya', 'Dizengoff Street', 175, 'West', 257);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (258, 'Beer Sheva', 'Rothschild Boulevard', 78, 'West', 258);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (259, 'Holon', 'Allenby Street', 135, 'Center', 259);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (260, 'Bnei Brak', 'King George Street', 64, 'East', 260);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (261, 'Rehovot', 'HaCarmel Market', 144, 'South', 261);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (262, 'Ashkelon', 'Nahalat Binyamin Street', 102, 'South', 262);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (263, 'Bat Yam', 'Herzl Street', 180, 'South', 263);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (264, 'Herzliya', 'Sderot Rothschild', 200, 'West', 264);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (265, 'Kfar Saba', 'Yehuda Halevi Street', 150, 'West', 265);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (266, 'Hadera', 'Ibn Gabirol Street', 57, 'West', 266);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (267, 'Modiin', 'Shenkin Street', 137, 'South', 267);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (268, 'Nazareth', 'Emek Refaim Street', 5, 'South', 268);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (269, 'Lod', 'Jaffa Street', 47, 'East', 269);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (270, 'Ramla', 'Beit Lehem Road', 106, 'West', 270);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (271, 'Afula', 'Ben Yehuda Street', 99, 'South', 271);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (272, 'Eilat', 'Dizengoff Street', 104, 'South', 272);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (273, 'Tiberias', 'Rothschild Boulevard', 157, 'West', 273);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (274, 'Kiryat Gat', 'Allenby Street', 167, 'East', 274);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (275, 'Yavne', 'King George Street', 62, 'South', 275);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (276, 'Nahariya', 'HaCarmel Market', 169, 'Center', 276);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (277, 'Raanana', 'Nahalat Binyamin Street', 164, 'North', 277);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (278, 'Givatayim', 'Herzl Street', 76, 'West', 278);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (279, 'Kiryat Ono', 'Sderot Rothschild', 52, 'West', 279);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (280, 'Rosh HaAyin', 'Yehuda Halevi Street', 4, 'North', 280);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (281, 'Yokneam', 'Ibn Gabirol Street', 63, 'East', 281);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (282, 'Zichron Yaakov', 'Shenkin Street', 146, 'West', 282);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (283, 'Caesarea', 'Emek Refaim Street', 4, 'South', 283);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (284, 'Pardes Hanna', 'Jaffa Street', 74, 'South', 284);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (285, 'Or Akiva', 'Beit Lehem Road', 107, 'North', 285);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (286, 'Karmiel', 'Ben Yehuda Street', 98, 'North', 286);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (287, 'Safed', 'Dizengoff Street', 16, 'West', 287);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (288, 'Migdal HaEmek', 'Rothschild Boulevard', 22, 'North', 288);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (289, 'Nof HaGalil', 'Allenby Street', 41, 'West', 289);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (290, 'Kiryat Shmona', 'King George Street', 106, 'North', 290);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (291, 'Dimona', 'HaCarmel Market', 30, 'North', 291);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (292, 'Arad', 'Nahalat Binyamin Street', 82, 'West', 292);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (293, 'Mevaseret Zion', 'Herzl Street', 92, 'South', 293);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (294, 'Maale Adumim', 'Sderot Rothschild', 74, 'South', 294);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (295, 'Beit Shemesh', 'Yehuda Halevi Street', 69, 'Center', 295);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (296, 'Nes Ziona', 'Ibn Gabirol Street', 26, 'East', 296);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (297, 'Shoham', 'Shenkin Street', 77, 'West', 297);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (298, 'Gedera', 'Emek Refaim Street', 86, 'West', 298);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (299, 'Gan Yavne', 'Jaffa Street', 63, 'West', 299);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (300, 'Kiryat Malakhi', 'Beit Lehem Road', 28, 'North', 300);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (301, 'Tel Aviv', 'Ben Yehuda Street', 63, 'North', 301);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (302, 'Jerusalem', 'Dizengoff Street', 152, 'Center', 302);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (303, 'Haifa', 'Rothschild Boulevard', 37, 'West', 303);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (304, 'Rishon LeZion', 'Allenby Street', 179, 'East', 304);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (305, 'Petah Tikva', 'King George Street', 170, 'Center', 305);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (306, 'Ashdod', 'HaCarmel Market', 8, 'North', 306);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (307, 'Netanya', 'Nahalat Binyamin Street', 147, 'West', 307);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (308, 'Beer Sheva', 'Herzl Street', 151, 'West', 308);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (309, 'Holon', 'Sderot Rothschild', 11, 'East', 309);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (310, 'Bnei Brak', 'Yehuda Halevi Street', 167, 'Center', 310);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (311, 'Rehovot', 'Ibn Gabirol Street', 162, 'South', 311);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (312, 'Ashkelon', 'Shenkin Street', 108, 'East', 312);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (313, 'Bat Yam', 'Emek Refaim Street', 57, 'North', 313);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (314, 'Herzliya', 'Jaffa Street', 102, 'East', 314);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (315, 'Kfar Saba', 'Beit Lehem Road', 196, 'North', 315);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (316, 'Hadera', 'Ben Yehuda Street', 104, 'East', 316);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (317, 'Modiin', 'Dizengoff Street', 142, 'North', 317);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (318, 'Nazareth', 'Rothschild Boulevard', 168, 'South', 318);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (319, 'Lod', 'Allenby Street', 129, 'Center', 319);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (320, 'Ramla', 'King George Street', 189, 'North', 320);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (321, 'Afula', 'HaCarmel Market', 173, 'North', 321);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (322, 'Eilat', 'Nahalat Binyamin Street', 184, 'North', 322);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (323, 'Tiberias', 'Herzl Street', 46, 'South', 323);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (324, 'Kiryat Gat', 'Sderot Rothschild', 123, 'Center', 324);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (325, 'Yavne', 'Yehuda Halevi Street', 69, 'West', 325);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (326, 'Nahariya', 'Ibn Gabirol Street', 88, 'South', 326);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (327, 'Raanana', 'Shenkin Street', 1, 'West', 327);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (328, 'Givatayim', 'Emek Refaim Street', 1, 'West', 328);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (329, 'Kiryat Ono', 'Jaffa Street', 132, 'South', 329);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (330, 'Rosh HaAyin', 'Beit Lehem Road', 15, 'West', 330);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (331, 'Yokneam', 'Ben Yehuda Street', 141, 'Center', 331);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (332, 'Zichron Yaakov', 'Dizengoff Street', 144, 'West', 332);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (333, 'Caesarea', 'Rothschild Boulevard', 132, 'East', 333);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (334, 'Pardes Hanna', 'Allenby Street', 81, 'South', 334);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (335, 'Or Akiva', 'King George Street', 43, 'East', 335);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (336, 'Karmiel', 'HaCarmel Market', 41, 'South', 336);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (337, 'Safed', 'Nahalat Binyamin Street', 151, 'Center', 337);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (338, 'Migdal HaEmek', 'Herzl Street', 69, 'South', 338);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (339, 'Nof HaGalil', 'Sderot Rothschild', 195, 'South', 339);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (340, 'Kiryat Shmona', 'Yehuda Halevi Street', 127, 'South', 340);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (341, 'Dimona', 'Ibn Gabirol Street', 69, 'South', 341);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (342, 'Arad', 'Shenkin Street', 152, 'North', 342);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (343, 'Mevaseret Zion', 'Emek Refaim Street', 200, 'North', 343);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (344, 'Maale Adumim', 'Jaffa Street', 67, 'West', 344);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (345, 'Beit Shemesh', 'Beit Lehem Road', 174, 'North', 345);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (346, 'Nes Ziona', 'Ben Yehuda Street', 23, 'Center', 346);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (347, 'Shoham', 'Dizengoff Street', 87, 'East', 347);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (348, 'Gedera', 'Rothschild Boulevard', 59, 'South', 348);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (349, 'Gan Yavne', 'Allenby Street', 45, 'West', 349);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (350, 'Kiryat Malakhi', 'King George Street', 111, 'Center', 350);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (351, 'Tel Aviv', 'HaCarmel Market', 13, 'North', 351);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (352, 'Jerusalem', 'Nahalat Binyamin Street', 42, 'East', 352);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (353, 'Haifa', 'Herzl Street', 13, 'East', 353);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (354, 'Rishon LeZion', 'Sderot Rothschild', 71, 'East', 354);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (355, 'Petah Tikva', 'Yehuda Halevi Street', 2, 'North', 355);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (356, 'Ashdod', 'Ibn Gabirol Street', 122, 'East', 356);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (357, 'Netanya', 'Shenkin Street', 148, 'East', 357);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (358, 'Beer Sheva', 'Emek Refaim Street', 10, 'West', 358);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (359, 'Holon', 'Jaffa Street', 116, 'North', 359);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (360, 'Bnei Brak', 'Beit Lehem Road', 141, 'West', 360);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (361, 'Rehovot', 'Ben Yehuda Street', 145, 'East', 361);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (362, 'Ashkelon', 'Dizengoff Street', 150, 'West', 362);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (363, 'Bat Yam', 'Rothschild Boulevard', 121, 'Center', 363);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (364, 'Herzliya', 'Allenby Street', 96, 'Center', 364);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (365, 'Kfar Saba', 'King George Street', 76, 'North', 365);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (366, 'Hadera', 'HaCarmel Market', 42, 'Center', 366);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (367, 'Modiin', 'Nahalat Binyamin Street', 171, 'North', 367);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (368, 'Nazareth', 'Herzl Street', 115, 'Center', 368);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (369, 'Lod', 'Sderot Rothschild', 149, 'North', 369);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (370, 'Ramla', 'Yehuda Halevi Street', 82, 'Center', 370);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (371, 'Afula', 'Ibn Gabirol Street', 140, 'Center', 371);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (372, 'Eilat', 'Shenkin Street', 196, 'Center', 372);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (373, 'Tiberias', 'Emek Refaim Street', 161, 'North', 373);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (374, 'Kiryat Gat', 'Jaffa Street', 144, 'Center', 374);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (375, 'Yavne', 'Beit Lehem Road', 115, 'East', 375);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (376, 'Nahariya', 'Ben Yehuda Street', 74, 'West', 376);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (377, 'Raanana', 'Dizengoff Street', 20, 'East', 377);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (378, 'Givatayim', 'Rothschild Boulevard', 166, 'South', 378);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (379, 'Kiryat Ono', 'Allenby Street', 142, 'East', 379);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (380, 'Rosh HaAyin', 'King George Street', 9, 'East', 380);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (381, 'Yokneam', 'HaCarmel Market', 7, 'East', 381);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (382, 'Zichron Yaakov', 'Nahalat Binyamin Street', 82, 'South', 382);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (383, 'Caesarea', 'Herzl Street', 171, 'East', 383);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (384, 'Pardes Hanna', 'Sderot Rothschild', 140, 'East', 384);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (385, 'Or Akiva', 'Yehuda Halevi Street', 31, 'North', 385);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (386, 'Karmiel', 'Ibn Gabirol Street', 59, 'North', 386);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (387, 'Safed', 'Shenkin Street', 72, 'East', 387);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (388, 'Migdal HaEmek', 'Emek Refaim Street', 2, 'East', 388);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (389, 'Nof HaGalil', 'Jaffa Street', 100, 'South', 389);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (390, 'Kiryat Shmona', 'Beit Lehem Road', 166, 'East', 390);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (391, 'Dimona', 'Ben Yehuda Street', 170, 'South', 391);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (392, 'Arad', 'Dizengoff Street', 47, 'East', 392);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (393, 'Mevaseret Zion', 'Rothschild Boulevard', 123, 'South', 393);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (394, 'Maale Adumim', 'Allenby Street', 110, 'North', 394);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (395, 'Beit Shemesh', 'King George Street', 133, 'East', 395);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (396, 'Nes Ziona', 'HaCarmel Market', 34, 'North', 396);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (397, 'Shoham', 'Nahalat Binyamin Street', 70, 'South', 397);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (398, 'Gedera', 'Herzl Street', 17, 'West', 398);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (399, 'Gan Yavne', 'Sderot Rothschild', 57, 'West', 399);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (400, 'Kiryat Malakhi', 'Yehuda Halevi Street', 25, 'West', 400);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (401, 'Tel Aviv', 'Ibn Gabirol Street', 177, 'Center', 401);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (402, 'Jerusalem', 'Shenkin Street', 58, 'West', 402);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (403, 'Haifa', 'Emek Refaim Street', 54, 'North', 403);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (404, 'Rishon LeZion', 'Jaffa Street', 47, 'East', 404);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (405, 'Petah Tikva', 'Beit Lehem Road', 184, 'South', 405);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (406, 'Ashdod', 'Ben Yehuda Street', 70, 'West', 406);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (407, 'Netanya', 'Dizengoff Street', 168, 'West', 407);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (408, 'Beer Sheva', 'Rothschild Boulevard', 200, 'Center', 408);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (409, 'Holon', 'Allenby Street', 36, 'North', 409);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (410, 'Bnei Brak', 'King George Street', 17, 'Center', 410);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (411, 'Rehovot', 'HaCarmel Market', 39, 'West', 411);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (412, 'Ashkelon', 'Nahalat Binyamin Street', 147, 'East', 412);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (413, 'Bat Yam', 'Herzl Street', 87, 'South', 413);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (414, 'Herzliya', 'Sderot Rothschild', 158, 'Center', 414);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (415, 'Kfar Saba', 'Yehuda Halevi Street', 30, 'East', 415);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (416, 'Hadera', 'Ibn Gabirol Street', 53, 'West', 416);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (417, 'Modiin', 'Shenkin Street', 118, 'West', 417);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (418, 'Nazareth', 'Emek Refaim Street', 52, 'West', 418);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (419, 'Lod', 'Jaffa Street', 121, 'East', 419);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (420, 'Ramla', 'Beit Lehem Road', 8, 'East', 420);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (421, 'Afula', 'Ben Yehuda Street', 186, 'South', 421);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (422, 'Eilat', 'Dizengoff Street', 56, 'West', 422);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (423, 'Tiberias', 'Rothschild Boulevard', 6, 'West', 423);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (424, 'Kiryat Gat', 'Allenby Street', 97, 'East', 424);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (425, 'Yavne', 'King George Street', 2, 'Center', 425);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (426, 'Nahariya', 'HaCarmel Market', 181, 'South', 426);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (427, 'Raanana', 'Nahalat Binyamin Street', 114, 'South', 427);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (428, 'Givatayim', 'Herzl Street', 113, 'East', 428);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (429, 'Kiryat Ono', 'Sderot Rothschild', 130, 'East', 429);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (430, 'Rosh HaAyin', 'Yehuda Halevi Street', 97, 'Center', 430);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (431, 'Yokneam', 'Ibn Gabirol Street', 128, 'South', 431);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (432, 'Zichron Yaakov', 'Shenkin Street', 165, 'Center', 432);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (433, 'Caesarea', 'Emek Refaim Street', 60, 'West', 433);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (434, 'Pardes Hanna', 'Jaffa Street', 143, 'East', 434);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (435, 'Or Akiva', 'Beit Lehem Road', 125, 'East', 435);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (436, 'Karmiel', 'Ben Yehuda Street', 18, 'Center', 436);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (437, 'Safed', 'Dizengoff Street', 143, 'East', 437);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (438, 'Migdal HaEmek', 'Rothschild Boulevard', 44, 'Center', 438);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (439, 'Nof HaGalil', 'Allenby Street', 132, 'North', 439);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (440, 'Kiryat Shmona', 'King George Street', 160, 'East', 440);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (441, 'Dimona', 'HaCarmel Market', 134, 'South', 441);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (442, 'Arad', 'Nahalat Binyamin Street', 28, 'Center', 442);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (443, 'Mevaseret Zion', 'Herzl Street', 113, 'North', 443);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (444, 'Maale Adumim', 'Sderot Rothschild', 70, 'South', 444);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (445, 'Beit Shemesh', 'Yehuda Halevi Street', 130, 'Center', 445);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (446, 'Nes Ziona', 'Ibn Gabirol Street', 173, 'East', 446);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (447, 'Shoham', 'Shenkin Street', 151, 'North', 447);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (448, 'Gedera', 'Emek Refaim Street', 32, 'West', 448);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (449, 'Gan Yavne', 'Jaffa Street', 145, 'West', 449);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (450, 'Kiryat Malakhi', 'Beit Lehem Road', 121, 'North', 450);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (451, 'Tel Aviv', 'Ben Yehuda Street', 98, 'South', 451);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (452, 'Jerusalem', 'Dizengoff Street', 165, 'North', 452);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (453, 'Haifa', 'Rothschild Boulevard', 181, 'South', 453);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (454, 'Rishon LeZion', 'Allenby Street', 172, 'Center', 454);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (455, 'Petah Tikva', 'King George Street', 129, 'South', 455);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (456, 'Ashdod', 'HaCarmel Market', 68, 'West', 456);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (457, 'Netanya', 'Nahalat Binyamin Street', 134, 'Center', 457);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (458, 'Beer Sheva', 'Herzl Street', 34, 'Center', 458);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (459, 'Holon', 'Sderot Rothschild', 72, 'Center', 459);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (460, 'Bnei Brak', 'Yehuda Halevi Street', 101, 'Center', 460);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (461, 'Rehovot', 'Ibn Gabirol Street', 73, 'South', 461);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (462, 'Ashkelon', 'Shenkin Street', 25, 'North', 462);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (463, 'Bat Yam', 'Emek Refaim Street', 43, 'South', 463);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (464, 'Herzliya', 'Jaffa Street', 21, 'West', 464);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (465, 'Kfar Saba', 'Beit Lehem Road', 57, 'Center', 465);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (466, 'Hadera', 'Ben Yehuda Street', 117, 'Center', 466);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (467, 'Modiin', 'Dizengoff Street', 98, 'North', 467);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (468, 'Nazareth', 'Rothschild Boulevard', 33, 'Center', 468);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (469, 'Lod', 'Allenby Street', 168, 'West', 469);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (470, 'Ramla', 'King George Street', 183, 'West', 470);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (471, 'Afula', 'HaCarmel Market', 153, 'Center', 471);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (472, 'Eilat', 'Nahalat Binyamin Street', 80, 'North', 472);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (473, 'Tiberias', 'Herzl Street', 132, 'West', 473);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (474, 'Kiryat Gat', 'Sderot Rothschild', 46, 'East', 474);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (475, 'Yavne', 'Yehuda Halevi Street', 141, 'West', 475);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (476, 'Nahariya', 'Ibn Gabirol Street', 57, 'South', 476);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (477, 'Raanana', 'Shenkin Street', 69, 'East', 477);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (478, 'Givatayim', 'Emek Refaim Street', 42, 'East', 478);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (479, 'Kiryat Ono', 'Jaffa Street', 192, 'Center', 479);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (480, 'Rosh HaAyin', 'Beit Lehem Road', 116, 'Center', 480);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (481, 'Yokneam', 'Ben Yehuda Street', 22, 'Center', 481);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (482, 'Zichron Yaakov', 'Dizengoff Street', 28, 'Center', 482);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (483, 'Caesarea', 'Rothschild Boulevard', 26, 'East', 483);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (484, 'Pardes Hanna', 'Allenby Street', 4, 'North', 484);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (485, 'Or Akiva', 'King George Street', 115, 'Center', 485);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (486, 'Karmiel', 'HaCarmel Market', 150, 'South', 486);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (487, 'Safed', 'Nahalat Binyamin Street', 43, 'East', 487);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (488, 'Migdal HaEmek', 'Herzl Street', 132, 'Center', 488);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (489, 'Nof HaGalil', 'Sderot Rothschild', 131, 'West', 489);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (490, 'Kiryat Shmona', 'Yehuda Halevi Street', 5, 'West', 490);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (491, 'Dimona', 'Ibn Gabirol Street', 60, 'North', 491);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (492, 'Arad', 'Shenkin Street', 193, 'West', 492);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (493, 'Mevaseret Zion', 'Emek Refaim Street', 68, 'North', 493);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (494, 'Maale Adumim', 'Jaffa Street', 4, 'East', 494);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (495, 'Beit Shemesh', 'Beit Lehem Road', 156, 'Center', 495);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (496, 'Nes Ziona', 'Ben Yehuda Street', 44, 'East', 496);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (497, 'Shoham', 'Dizengoff Street', 86, 'West', 497);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (498, 'Gedera', 'Rothschild Boulevard', 97, 'West', 498);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (499, 'Gan Yavne', 'Allenby Street', 170, 'West', 499);
insert into LOCATION (LocationID, City, Street, StreetNumber, Region, StoreID) values (500, 'Kiryat Malakhi', 'King George Street', 167, 'South', 500);
