INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (1, 'Yael', 'Cohen', 'Inactive', 8938.7, 'Store Manager', 1);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (2, 'Yael', 'Amar', 'Active', 13085.91, 'Cashier', 2);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (3, 'Noam', 'Levi', 'Active', 8791.93, 'Customer Service Representative', 3);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (4, 'Noam', 'Amar', 'Active', 14592.24, 'Department Manager', 4);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (5, 'Omri', 'Avraham', 'Active', 11390.51, 'Shift Manager', 5);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (6, 'Noam', 'Mizrahi', 'Inactive', 10083.01, 'Store Manager', 6);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (7, 'Roni', 'Malka', 'Active', 7112.95, 'Cashier', 7);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (8, 'Lior', 'Malka', 'Inactive', 15685.54, 'Department Manager', 8);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (9, 'Yarden', 'Amar', 'Active', 17677.39, 'Stock Clerk', 9);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (10, 'Yael', 'Amar', 'Inactive', 15952.86, 'Customer Service Representative', 10);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (11, 'Lior', 'Haddad', 'Active', 14454.86, 'Cashier', 11);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (12, 'Roni', 'Biton', 'Active', 16263.81, 'Cashier', 12);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (13, 'Neta', 'Biton', 'Inactive', 13628.21, 'Shift Manager', 13);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (14, 'Dana', 'Malka', 'Inactive', 8514.08, 'Shift Manager', 14);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (15, 'Yael', 'Haddad', 'Active', 12409.68, 'Store Manager', 15);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (16, 'Dana', 'Dahan', 'Inactive', 9239.37, 'Department Manager', 16);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (17, 'Omri', 'Peretz', 'Inactive', 16114.22, 'Cashier', 17);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (18, 'Roni', 'Cohen', 'Inactive', 10813.98, 'Cashier', 18);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (19, 'Roni', 'Haddad', 'Inactive', 8551.52, 'Stock Clerk', 19);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (20, 'Neta', 'Dahan', 'Active', 9178.56, 'Store Manager', 20);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (21, 'Omri', 'Amar', 'Inactive', 14964.17, 'Stock Clerk', 21);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (22, 'Eden', 'Avraham', 'Inactive', 8631.85, 'Store Manager', 22);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (23, 'Omri', 'Dahan', 'Active', 15069.39, 'Cashier', 23);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (24, 'Dana', 'Mizrahi', 'Inactive', 13156.91, 'Stock Clerk', 24);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (25, 'Neta', 'Haddad', 'Inactive', 12349.37, 'Customer Service Representative', 25);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (26, 'Noam', 'Levi', 'Inactive', 15223.18, 'Shift Manager', 26);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (27, 'Yael', 'Biton', 'Inactive', 7897.89, 'Cashier', 27);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (28, 'Maya', 'Amar', 'Active', 12092.18, 'Cashier', 28);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (29, 'Maya', 'Amar', 'Active', 7834.07, 'Store Manager', 29);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (30, 'Omri', 'Amar', 'Active', 13187.34, 'Stock Clerk', 30);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (31, 'Noam', 'Levi', 'Inactive', 16544.66, 'Shift Manager', 31);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (32, 'Roni', 'Cohen', 'Active', 16536.12, 'Cashier', 32);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (33, 'Yael', 'Dahan', 'Active', 17735.81, 'Customer Service Representative', 33);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (34, 'Dana', 'Mizrahi', 'Inactive', 17362.18, 'Store Manager', 34);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (35, 'Maya', 'Amar', 'Inactive', 17572.35, 'Customer Service Representative', 35);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (36, 'Roni', 'Biton', 'Inactive', 17941.79, 'Department Manager', 36);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (37, 'Lior', 'Dahan', 'Inactive', 7452.05, 'Store Manager', 37);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (38, 'Yael', 'Malka', 'Active', 13059.7, 'Store Manager', 38);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (39, 'Eden', 'Peretz', 'Active', 6851.92, 'Department Manager', 39);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (40, 'Noam', 'Peretz', 'Active', 16865.04, 'Shift Manager', 40);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (41, 'Yael', 'Amar', 'Active', 9341.73, 'Stock Clerk', 41);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (42, 'Roni', 'Amar', 'Active', 14680.23, 'Customer Service Representative', 42);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (43, 'Eden', 'Dahan', 'Active', 15415.43, 'Stock Clerk', 43);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (44, 'Roni', 'Levi', 'Active', 13907.79, 'Shift Manager', 44);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (45, 'Neta', 'Avraham', 'Inactive', 16366.04, 'Cashier', 45);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (46, 'Yael', 'Cohen', 'Inactive', 14738.56, 'Cashier', 46);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (47, 'Roni', 'Peretz', 'Active', 12435.43, 'Store Manager', 47);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (48, 'Neta', 'Mizrahi', 'Inactive', 11551.54, 'Cashier', 48);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (49, 'Yarden', 'Amar', 'Active', 6607.06, 'Customer Service Representative', 49);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (50, 'Noam', 'Levi', 'Active', 7995.73, 'Stock Clerk', 50);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (51, 'Yarden', 'Peretz', 'Inactive', 16829.31, 'Store Manager', 51);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (52, 'Neta', 'Cohen', 'Inactive', 9182.44, 'Stock Clerk', 52);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (53, 'Maya', 'Avraham', 'Inactive', 7857.56, 'Shift Manager', 53);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (54, 'Roni', 'Cohen', 'Active', 14975.71, 'Cashier', 54);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (55, 'Noam', 'Haddad', 'Inactive', 12034.2, 'Customer Service Representative', 55);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (56, 'Dana', 'Cohen', 'Active', 16216.11, 'Cashier', 56);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (57, 'Eden', 'Levi', 'Active', 10845.31, 'Customer Service Representative', 57);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (58, 'Roni', 'Haddad', 'Active', 13432.58, 'Stock Clerk', 58);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (59, 'Eden', 'Haddad', 'Inactive', 17216.48, 'Store Manager', 59);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (60, 'Lior', 'Peretz', 'Inactive', 10749.43, 'Department Manager', 60);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (61, 'Maya', 'Dahan', 'Inactive', 17148.22, 'Cashier', 61);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (62, 'Noam', 'Dahan', 'Active', 6879.13, 'Store Manager', 62);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (63, 'Omri', 'Biton', 'Active', 17199.11, 'Cashier', 63);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (64, 'Roni', 'Malka', 'Inactive', 7892.96, 'Customer Service Representative', 64);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (65, 'Maya', 'Haddad', 'Active', 14014.36, 'Customer Service Representative', 65);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (66, 'Maya', 'Levi', 'Active', 9173.59, 'Cashier', 66);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (67, 'Omri', 'Mizrahi', 'Inactive', 9381.08, 'Store Manager', 67);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (68, 'Lior', 'Peretz', 'Inactive', 12064.91, 'Shift Manager', 68);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (69, 'Noam', 'Levi', 'Inactive', 15952.18, 'Cashier', 69);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (70, 'Noam', 'Malka', 'Active', 13645.36, 'Shift Manager', 70);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (71, 'Dana', 'Dahan', 'Inactive', 12730.88, 'Cashier', 71);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (72, 'Yael', 'Mizrahi', 'Active', 16015.14, 'Customer Service Representative', 72);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (73, 'Omri', 'Mizrahi', 'Inactive', 7529.35, 'Shift Manager', 73);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (74, 'Lior', 'Cohen', 'Inactive', 8520.92, 'Store Manager', 74);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (75, 'Yael', 'Malka', 'Inactive', 17686.04, 'Department Manager', 75);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (76, 'Dana', 'Peretz', 'Active', 17714.47, 'Store Manager', 76);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (77, 'Neta', 'Cohen', 'Active', 14838.77, 'Shift Manager', 77);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (78, 'Neta', 'Peretz', 'Inactive', 7910.37, 'Department Manager', 78);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (79, 'Yael', 'Avraham', 'Active', 16303.12, 'Store Manager', 79);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (80, 'Roni', 'Dahan', 'Inactive', 9662.29, 'Store Manager', 80);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (81, 'Roni', 'Cohen', 'Active', 10781.59, 'Shift Manager', 81);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (82, 'Yael', 'Biton', 'Inactive', 13697.78, 'Stock Clerk', 82);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (83, 'Omri', 'Malka', 'Active', 7384.1, 'Shift Manager', 83);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (84, 'Dana', 'Haddad', 'Inactive', 6459.09, 'Customer Service Representative', 84);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (85, 'Neta', 'Malka', 'Inactive', 11236.73, 'Customer Service Representative', 85);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (86, 'Yael', 'Avraham', 'Active', 9056.67, 'Department Manager', 86);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (87, 'Neta', 'Cohen', 'Active', 10370.66, 'Cashier', 87);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (88, 'Lior', 'Haddad', 'Inactive', 13960.65, 'Cashier', 88);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (89, 'Maya', 'Amar', 'Inactive', 14002.71, 'Shift Manager', 89);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (90, 'Neta', 'Biton', 'Active', 8302.08, 'Department Manager', 90);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (91, 'Neta', 'Mizrahi', 'Inactive', 10872.9, 'Cashier', 91);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (92, 'Maya', 'Biton', 'Active', 11158.66, 'Customer Service Representative', 92);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (93, 'Eden', 'Malka', 'Inactive', 11301.43, 'Department Manager', 93);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (94, 'Roni', 'Amar', 'Inactive', 15524.82, 'Department Manager', 94);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (95, 'Dana', 'Levi', 'Inactive', 12185.42, 'Department Manager', 95);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (96, 'Eden', 'Malka', 'Active', 15821.08, 'Store Manager', 96);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (97, 'Maya', 'Peretz', 'Active', 7768.25, 'Cashier', 97);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (98, 'Roni', 'Dahan', 'Active', 11464.99, 'Department Manager', 98);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (99, 'Eden', 'Peretz', 'Inactive', 11932.53, 'Store Manager', 99);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (100, 'Dana', 'Cohen', 'Active', 15341.04, 'Store Manager', 100);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (101, 'Dana', 'Amar', 'Inactive', 6602.62, 'Store Manager', 101);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (102, 'Yael', 'Dahan', 'Active', 15617.0, 'Department Manager', 102);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (103, 'Omri', 'Amar', 'Inactive', 17400.48, 'Stock Clerk', 103);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (104, 'Eden', 'Amar', 'Inactive', 15966.83, 'Customer Service Representative', 104);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (105, 'Yarden', 'Mizrahi', 'Inactive', 11400.84, 'Store Manager', 105);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (106, 'Maya', 'Amar', 'Inactive', 13520.98, 'Shift Manager', 106);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (107, 'Yarden', 'Levi', 'Inactive', 8813.92, 'Shift Manager', 107);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (108, 'Lior', 'Amar', 'Active', 7660.49, 'Store Manager', 108);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (109, 'Neta', 'Mizrahi', 'Active', 6770.75, 'Stock Clerk', 109);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (110, 'Lior', 'Amar', 'Inactive', 10989.29, 'Store Manager', 110);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (111, 'Neta', 'Avraham', 'Active', 16280.78, 'Customer Service Representative', 111);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (112, 'Neta', 'Dahan', 'Active', 17312.9, 'Shift Manager', 112);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (113, 'Neta', 'Avraham', 'Active', 11858.75, 'Shift Manager', 113);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (114, 'Neta', 'Dahan', 'Active', 10666.29, 'Department Manager', 114);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (115, 'Neta', 'Mizrahi', 'Inactive', 17034.5, 'Customer Service Representative', 115);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (116, 'Omri', 'Cohen', 'Inactive', 13102.71, 'Department Manager', 116);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (117, 'Noam', 'Levi', 'Inactive', 7628.39, 'Stock Clerk', 117);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (118, 'Dana', 'Cohen', 'Inactive', 10549.25, 'Store Manager', 118);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (119, 'Yarden', 'Malka', 'Inactive', 15134.76, 'Stock Clerk', 119);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (120, 'Maya', 'Avraham', 'Inactive', 16018.93, 'Stock Clerk', 120);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (121, 'Noam', 'Amar', 'Active', 17998.89, 'Shift Manager', 121);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (122, 'Roni', 'Levi', 'Active', 15050.8, 'Store Manager', 122);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (123, 'Roni', 'Cohen', 'Active', 8862.54, 'Stock Clerk', 123);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (124, 'Yael', 'Haddad', 'Active', 11580.41, 'Shift Manager', 124);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (125, 'Lior', 'Mizrahi', 'Active', 15333.5, 'Store Manager', 125);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (126, 'Maya', 'Levi', 'Active', 17146.65, 'Customer Service Representative', 126);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (127, 'Neta', 'Avraham', 'Active', 6911.96, 'Department Manager', 127);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (128, 'Roni', 'Levi', 'Inactive', 16203.52, 'Customer Service Representative', 128);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (129, 'Yael', 'Haddad', 'Active', 10166.45, 'Stock Clerk', 129);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (130, 'Lior', 'Levi', 'Inactive', 6151.83, 'Stock Clerk', 130);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (131, 'Yarden', 'Levi', 'Inactive', 17529.45, 'Department Manager', 131);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (132, 'Yarden', 'Mizrahi', 'Inactive', 8113.64, 'Customer Service Representative', 132);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (133, 'Maya', 'Haddad', 'Inactive', 11578.49, 'Department Manager', 133);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (134, 'Eden', 'Biton', 'Inactive', 16220.56, 'Cashier', 134);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (135, 'Maya', 'Dahan', 'Active', 15005.72, 'Customer Service Representative', 135);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (136, 'Eden', 'Avraham', 'Inactive', 6344.4, 'Shift Manager', 136);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (137, 'Dana', 'Dahan', 'Active', 10257.9, 'Shift Manager', 137);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (138, 'Lior', 'Biton', 'Inactive', 12669.49, 'Customer Service Representative', 138);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (139, 'Roni', 'Levi', 'Active', 14640.9, 'Stock Clerk', 139);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (140, 'Omri', 'Peretz', 'Inactive', 13750.83, 'Stock Clerk', 140);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (141, 'Yarden', 'Cohen', 'Active', 9530.83, 'Stock Clerk', 141);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (142, 'Roni', 'Biton', 'Inactive', 11679.13, 'Customer Service Representative', 142);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (143, 'Lior', 'Avraham', 'Inactive', 10221.73, 'Stock Clerk', 143);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (144, 'Maya', 'Biton', 'Inactive', 8766.46, 'Department Manager', 144);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (145, 'Roni', 'Malka', 'Active', 14914.57, 'Department Manager', 145);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (146, 'Dana', 'Peretz', 'Active', 14863.26, 'Shift Manager', 146);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (147, 'Eden', 'Amar', 'Inactive', 17766.13, 'Store Manager', 147);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (148, 'Maya', 'Peretz', 'Inactive', 8153.3, 'Cashier', 148);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (149, 'Omri', 'Mizrahi', 'Inactive', 6546.19, 'Cashier', 149);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (150, 'Omri', 'Biton', 'Active', 13654.44, 'Stock Clerk', 150);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (151, 'Yael', 'Cohen', 'Inactive', 11632.76, 'Stock Clerk', 151);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (152, 'Lior', 'Mizrahi', 'Active', 9029.74, 'Stock Clerk', 152);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (153, 'Yael', 'Levi', 'Inactive', 11900.96, 'Customer Service Representative', 153);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (154, 'Noam', 'Mizrahi', 'Active', 15733.7, 'Shift Manager', 154);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (155, 'Yael', 'Peretz', 'Active', 12696.88, 'Stock Clerk', 155);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (156, 'Eden', 'Haddad', 'Active', 15308.32, 'Stock Clerk', 156);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (157, 'Yarden', 'Dahan', 'Inactive', 16322.0, 'Stock Clerk', 157);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (158, 'Maya', 'Haddad', 'Active', 13315.57, 'Department Manager', 158);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (159, 'Yael', 'Peretz', 'Active', 9175.75, 'Cashier', 159);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (160, 'Dana', 'Peretz', 'Active', 12623.91, 'Store Manager', 160);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (161, 'Noam', 'Avraham', 'Inactive', 14272.45, 'Stock Clerk', 161);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (162, 'Maya', 'Cohen', 'Active', 9457.26, 'Shift Manager', 162);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (163, 'Yarden', 'Levi', 'Active', 17086.93, 'Department Manager', 163);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (164, 'Eden', 'Peretz', 'Inactive', 7377.32, 'Store Manager', 164);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (165, 'Dana', 'Biton', 'Active', 6856.92, 'Store Manager', 165);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (166, 'Maya', 'Haddad', 'Inactive', 11269.84, 'Stock Clerk', 166);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (167, 'Maya', 'Avraham', 'Inactive', 12005.67, 'Stock Clerk', 167);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (168, 'Yarden', 'Levi', 'Active', 16673.07, 'Department Manager', 168);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (169, 'Lior', 'Haddad', 'Inactive', 6310.38, 'Store Manager', 169);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (170, 'Eden', 'Haddad', 'Active', 17994.87, 'Department Manager', 170);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (171, 'Maya', 'Haddad', 'Active', 15157.31, 'Store Manager', 171);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (172, 'Yarden', 'Amar', 'Inactive', 16992.87, 'Store Manager', 172);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (173, 'Eden', 'Avraham', 'Inactive', 17628.66, 'Stock Clerk', 173);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (174, 'Lior', 'Avraham', 'Inactive', 9852.7, 'Cashier', 174);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (175, 'Dana', 'Malka', 'Inactive', 14324.08, 'Shift Manager', 175);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (176, 'Neta', 'Amar', 'Active', 11457.91, 'Shift Manager', 176);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (177, 'Maya', 'Malka', 'Active', 17642.22, 'Stock Clerk', 177);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (178, 'Omri', 'Cohen', 'Inactive', 10958.97, 'Store Manager', 178);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (179, 'Omri', 'Malka', 'Inactive', 13504.9, 'Cashier', 179);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (180, 'Roni', 'Biton', 'Active', 17132.07, 'Stock Clerk', 180);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (181, 'Yarden', 'Levi', 'Active', 17677.76, 'Customer Service Representative', 181);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (182, 'Roni', 'Mizrahi', 'Inactive', 12610.07, 'Customer Service Representative', 182);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (183, 'Neta', 'Levi', 'Active', 17907.09, 'Cashier', 183);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (184, 'Yarden', 'Levi', 'Active', 11980.51, 'Department Manager', 184);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (185, 'Maya', 'Amar', 'Inactive', 10985.88, 'Stock Clerk', 185);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (186, 'Yarden', 'Peretz', 'Inactive', 12615.18, 'Stock Clerk', 186);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (187, 'Roni', 'Haddad', 'Active', 16368.32, 'Shift Manager', 187);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (188, 'Neta', 'Malka', 'Inactive', 15846.59, 'Shift Manager', 188);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (189, 'Maya', 'Haddad', 'Inactive', 16383.13, 'Stock Clerk', 189);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (190, 'Omri', 'Dahan', 'Inactive', 9989.28, 'Customer Service Representative', 190);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (191, 'Neta', 'Dahan', 'Inactive', 16435.22, 'Department Manager', 191);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (192, 'Roni', 'Haddad', 'Inactive', 8802.75, 'Stock Clerk', 192);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (193, 'Noam', 'Malka', 'Inactive', 14462.73, 'Stock Clerk', 193);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (194, 'Neta', 'Mizrahi', 'Inactive', 17577.89, 'Store Manager', 194);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (195, 'Omri', 'Haddad', 'Inactive', 16436.4, 'Stock Clerk', 195);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (196, 'Yael', 'Amar', 'Inactive', 6184.17, 'Store Manager', 196);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (197, 'Neta', 'Mizrahi', 'Active', 11633.89, 'Shift Manager', 197);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (198, 'Lior', 'Haddad', 'Inactive', 13798.04, 'Shift Manager', 198);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (199, 'Omri', 'Avraham', 'Inactive', 13521.59, 'Stock Clerk', 199);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (200, 'Omri', 'Cohen', 'Active', 8817.24, 'Department Manager', 200);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (201, 'Maya', 'Peretz', 'Active', 11207.66, 'Cashier', 201);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (202, 'Yael', 'Dahan', 'Active', 14328.01, 'Cashier', 202);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (203, 'Noam', 'Malka', 'Active', 9520.41, 'Shift Manager', 203);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (204, 'Neta', 'Mizrahi', 'Active', 12374.0, 'Customer Service Representative', 204);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (205, 'Dana', 'Mizrahi', 'Active', 6947.62, 'Stock Clerk', 205);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (206, 'Eden', 'Peretz', 'Inactive', 16953.95, 'Store Manager', 206);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (207, 'Roni', 'Dahan', 'Inactive', 11514.85, 'Department Manager', 207);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (208, 'Noam', 'Dahan', 'Inactive', 14131.33, 'Store Manager', 208);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (209, 'Yael', 'Dahan', 'Inactive', 17851.82, 'Shift Manager', 209);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (210, 'Neta', 'Biton', 'Inactive', 16143.65, 'Store Manager', 210);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (211, 'Neta', 'Dahan', 'Active', 8846.47, 'Customer Service Representative', 211);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (212, 'Lior', 'Haddad', 'Inactive', 17912.3, 'Shift Manager', 212);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (213, 'Noam', 'Avraham', 'Inactive', 6097.18, 'Department Manager', 213);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (214, 'Noam', 'Haddad', 'Inactive', 15994.07, 'Shift Manager', 214);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (215, 'Roni', 'Haddad', 'Inactive', 8628.05, 'Store Manager', 215);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (216, 'Eden', 'Biton', 'Active', 13538.98, 'Department Manager', 216);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (217, 'Noam', 'Biton', 'Inactive', 6400.37, 'Shift Manager', 217);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (218, 'Dana', 'Levi', 'Inactive', 9920.63, 'Stock Clerk', 218);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (219, 'Dana', 'Peretz', 'Active', 15438.15, 'Shift Manager', 219);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (220, 'Omri', 'Amar', 'Inactive', 15965.67, 'Shift Manager', 220);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (221, 'Yarden', 'Biton', 'Inactive', 15650.79, 'Stock Clerk', 221);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (222, 'Yael', 'Mizrahi', 'Active', 16321.69, 'Department Manager', 222);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (223, 'Neta', 'Amar', 'Inactive', 7083.63, 'Stock Clerk', 223);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (224, 'Noam', 'Biton', 'Active', 11457.43, 'Department Manager', 224);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (225, 'Maya', 'Haddad', 'Inactive', 15869.01, 'Shift Manager', 225);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (226, 'Yael', 'Peretz', 'Inactive', 6300.3, 'Customer Service Representative', 226);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (227, 'Lior', 'Haddad', 'Active', 13771.83, 'Department Manager', 227);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (228, 'Yarden', 'Biton', 'Inactive', 7400.11, 'Cashier', 228);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (229, 'Noam', 'Biton', 'Inactive', 7393.45, 'Store Manager', 229);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (230, 'Omri', 'Mizrahi', 'Inactive', 11443.73, 'Department Manager', 230);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (231, 'Omri', 'Avraham', 'Active', 16624.97, 'Department Manager', 231);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (232, 'Yael', 'Dahan', 'Inactive', 17268.64, 'Shift Manager', 232);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (233, 'Noam', 'Malka', 'Active', 11320.6, 'Store Manager', 233);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (234, 'Lior', 'Levi', 'Inactive', 12533.59, 'Department Manager', 234);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (235, 'Lior', 'Cohen', 'Inactive', 9310.58, 'Cashier', 235);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (236, 'Yarden', 'Levi', 'Active', 13700.45, 'Customer Service Representative', 236);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (237, 'Noam', 'Cohen', 'Inactive', 8922.83, 'Store Manager', 237);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (238, 'Eden', 'Peretz', 'Active', 15957.81, 'Customer Service Representative', 238);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (239, 'Roni', 'Haddad', 'Active', 15756.64, 'Store Manager', 239);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (240, 'Lior', 'Mizrahi', 'Active', 9327.3, 'Store Manager', 240);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (241, 'Dana', 'Amar', 'Inactive', 15582.17, 'Cashier', 241);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (242, 'Noam', 'Mizrahi', 'Active', 10298.91, 'Store Manager', 242);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (243, 'Eden', 'Malka', 'Active', 8090.95, 'Cashier', 243);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (244, 'Dana', 'Avraham', 'Active', 14947.98, 'Stock Clerk', 244);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (245, 'Yarden', 'Malka', 'Active', 11424.07, 'Store Manager', 245);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (246, 'Eden', 'Cohen', 'Inactive', 11496.51, 'Cashier', 246);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (247, 'Noam', 'Dahan', 'Inactive', 11115.28, 'Cashier', 247);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (248, 'Yarden', 'Dahan', 'Active', 16791.2, 'Shift Manager', 248);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (249, 'Eden', 'Mizrahi', 'Active', 7514.3, 'Customer Service Representative', 249);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (250, 'Eden', 'Amar', 'Inactive', 10570.85, 'Customer Service Representative', 250);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (251, 'Omri', 'Biton', 'Inactive', 12066.61, 'Stock Clerk', 251);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (252, 'Yael', 'Levi', 'Active', 11160.84, 'Store Manager', 252);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (253, 'Neta', 'Malka', 'Inactive', 10784.76, 'Department Manager', 253);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (254, 'Yael', 'Malka', 'Inactive', 9750.28, 'Shift Manager', 254);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (255, 'Lior', 'Mizrahi', 'Inactive', 6805.6, 'Cashier', 255);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (256, 'Yael', 'Avraham', 'Active', 14935.07, 'Shift Manager', 256);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (257, 'Dana', 'Amar', 'Active', 13037.58, 'Customer Service Representative', 257);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (258, 'Omri', 'Malka', 'Active', 10929.7, 'Department Manager', 258);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (259, 'Neta', 'Cohen', 'Inactive', 13204.92, 'Shift Manager', 259);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (260, 'Yael', 'Haddad', 'Active', 7856.76, 'Stock Clerk', 260);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (261, 'Roni', 'Levi', 'Inactive', 16144.48, 'Shift Manager', 261);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (262, 'Yael', 'Biton', 'Active', 15686.66, 'Customer Service Representative', 262);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (263, 'Eden', 'Haddad', 'Active', 13307.94, 'Department Manager', 263);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (264, 'Maya', 'Cohen', 'Active', 9279.24, 'Shift Manager', 264);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (265, 'Lior', 'Malka', 'Active', 8176.87, 'Store Manager', 265);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (266, 'Eden', 'Avraham', 'Active', 7702.5, 'Department Manager', 266);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (267, 'Noam', 'Levi', 'Active', 10514.33, 'Stock Clerk', 267);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (268, 'Lior', 'Mizrahi', 'Inactive', 9739.65, 'Shift Manager', 268);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (269, 'Eden', 'Haddad', 'Active', 16600.11, 'Store Manager', 269);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (270, 'Dana', 'Haddad', 'Active', 14087.62, 'Shift Manager', 270);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (271, 'Yarden', 'Avraham', 'Inactive', 13284.91, 'Stock Clerk', 271);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (272, 'Maya', 'Peretz', 'Active', 10142.07, 'Cashier', 272);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (273, 'Maya', 'Haddad', 'Inactive', 12323.21, 'Shift Manager', 273);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (274, 'Noam', 'Peretz', 'Inactive', 17813.35, 'Cashier', 274);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (275, 'Noam', 'Peretz', 'Inactive', 17343.89, 'Store Manager', 275);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (276, 'Maya', 'Biton', 'Inactive', 7439.81, 'Stock Clerk', 276);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (277, 'Neta', 'Mizrahi', 'Active', 10562.49, 'Department Manager', 277);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (278, 'Roni', 'Amar', 'Inactive', 6864.91, 'Department Manager', 278);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (279, 'Noam', 'Avraham', 'Active', 11517.05, 'Cashier', 279);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (280, 'Lior', 'Haddad', 'Inactive', 12880.8, 'Department Manager', 280);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (281, 'Neta', 'Biton', 'Active', 10860.39, 'Shift Manager', 281);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (282, 'Dana', 'Haddad', 'Inactive', 15984.31, 'Shift Manager', 282);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (283, 'Yael', 'Avraham', 'Active', 8919.8, 'Customer Service Representative', 283);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (284, 'Neta', 'Amar', 'Active', 10749.2, 'Shift Manager', 284);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (285, 'Lior', 'Peretz', 'Inactive', 15349.41, 'Cashier', 285);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (286, 'Omri', 'Levi', 'Active', 16871.07, 'Shift Manager', 286);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (287, 'Lior', 'Mizrahi', 'Active', 7233.65, 'Shift Manager', 287);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (288, 'Roni', 'Mizrahi', 'Active', 15122.58, 'Department Manager', 288);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (289, 'Yael', 'Mizrahi', 'Inactive', 11567.44, 'Customer Service Representative', 289);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (290, 'Eden', 'Dahan', 'Inactive', 16370.96, 'Department Manager', 290);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (291, 'Lior', 'Mizrahi', 'Inactive', 6819.44, 'Stock Clerk', 291);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (292, 'Maya', 'Biton', 'Active', 10223.31, 'Cashier', 292);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (293, 'Maya', 'Dahan', 'Inactive', 6451.29, 'Shift Manager', 293);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (294, 'Maya', 'Levi', 'Active', 13380.1, 'Customer Service Representative', 294);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (295, 'Neta', 'Dahan', 'Active', 11396.8, 'Customer Service Representative', 295);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (296, 'Roni', 'Malka', 'Inactive', 12016.41, 'Cashier', 296);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (297, 'Yarden', 'Levi', 'Inactive', 17788.63, 'Cashier', 297);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (298, 'Omri', 'Mizrahi', 'Active', 8972.92, 'Stock Clerk', 298);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (299, 'Yarden', 'Amar', 'Active', 10366.78, 'Shift Manager', 299);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (300, 'Neta', 'Avraham', 'Inactive', 14146.77, 'Cashier', 300);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (301, 'Lior', 'Levi', 'Inactive', 7134.07, 'Department Manager', 301);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (302, 'Neta', 'Biton', 'Inactive', 14684.8, 'Department Manager', 302);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (303, 'Eden', 'Mizrahi', 'Inactive', 6978.02, 'Department Manager', 303);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (304, 'Dana', 'Malka', 'Inactive', 17612.36, 'Department Manager', 304);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (305, 'Neta', 'Mizrahi', 'Active', 9714.98, 'Stock Clerk', 305);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (306, 'Lior', 'Mizrahi', 'Active', 13752.3, 'Stock Clerk', 306);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (307, 'Omri', 'Malka', 'Active', 10351.17, 'Store Manager', 307);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (308, 'Roni', 'Malka', 'Inactive', 8304.06, 'Store Manager', 308);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (309, 'Dana', 'Levi', 'Inactive', 16133.14, 'Cashier', 309);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (310, 'Omri', 'Amar', 'Active', 13943.15, 'Customer Service Representative', 310);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (311, 'Dana', 'Haddad', 'Inactive', 7851.03, 'Store Manager', 311);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (312, 'Eden', 'Mizrahi', 'Inactive', 6524.31, 'Shift Manager', 312);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (313, 'Roni', 'Dahan', 'Inactive', 15028.69, 'Stock Clerk', 313);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (314, 'Roni', 'Amar', 'Active', 9713.61, 'Stock Clerk', 314);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (315, 'Roni', 'Malka', 'Inactive', 11540.16, 'Shift Manager', 315);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (316, 'Neta', 'Amar', 'Inactive', 17595.22, 'Store Manager', 316);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (317, 'Eden', 'Mizrahi', 'Inactive', 6626.16, 'Stock Clerk', 317);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (318, 'Lior', 'Amar', 'Active', 14536.81, 'Customer Service Representative', 318);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (319, 'Yael', 'Biton', 'Active', 15157.4, 'Shift Manager', 319);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (320, 'Yarden', 'Amar', 'Active', 15972.56, 'Cashier', 320);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (321, 'Roni', 'Dahan', 'Inactive', 17165.66, 'Stock Clerk', 321);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (322, 'Noam', 'Avraham', 'Inactive', 8829.34, 'Cashier', 322);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (323, 'Lior', 'Peretz', 'Active', 9824.22, 'Cashier', 323);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (324, 'Lior', 'Mizrahi', 'Active', 6459.64, 'Stock Clerk', 324);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (325, 'Dana', 'Dahan', 'Inactive', 13384.18, 'Cashier', 325);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (326, 'Noam', 'Biton', 'Active', 16019.56, 'Customer Service Representative', 326);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (327, 'Eden', 'Amar', 'Inactive', 7334.24, 'Shift Manager', 327);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (328, 'Roni', 'Biton', 'Active', 6572.99, 'Stock Clerk', 328);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (329, 'Eden', 'Dahan', 'Active', 7330.29, 'Stock Clerk', 329);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (330, 'Eden', 'Amar', 'Active', 13583.46, 'Customer Service Representative', 330);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (331, 'Roni', 'Mizrahi', 'Inactive', 11150.87, 'Customer Service Representative', 331);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (332, 'Lior', 'Peretz', 'Inactive', 8247.77, 'Department Manager', 332);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (333, 'Yael', 'Amar', 'Inactive', 6812.15, 'Customer Service Representative', 333);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (334, 'Omri', 'Amar', 'Active', 10685.44, 'Stock Clerk', 334);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (335, 'Noam', 'Avraham', 'Inactive', 9043.8, 'Cashier', 335);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (336, 'Lior', 'Levi', 'Inactive', 8893.51, 'Department Manager', 336);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (337, 'Yael', 'Haddad', 'Inactive', 7600.92, 'Shift Manager', 337);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (338, 'Omri', 'Malka', 'Active', 15964.6, 'Department Manager', 338);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (339, 'Yarden', 'Dahan', 'Active', 15737.97, 'Cashier', 339);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (340, 'Yarden', 'Cohen', 'Inactive', 8419.09, 'Store Manager', 340);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (341, 'Noam', 'Malka', 'Inactive', 12184.6, 'Customer Service Representative', 341);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (342, 'Yarden', 'Biton', 'Active', 15039.49, 'Store Manager', 342);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (343, 'Maya', 'Malka', 'Active', 16389.58, 'Shift Manager', 343);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (344, 'Maya', 'Levi', 'Inactive', 11243.42, 'Stock Clerk', 344);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (345, 'Yarden', 'Avraham', 'Inactive', 17684.68, 'Stock Clerk', 345);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (346, 'Yarden', 'Malka', 'Inactive', 15613.78, 'Department Manager', 346);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (347, 'Neta', 'Levi', 'Inactive', 13229.44, 'Store Manager', 347);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (348, 'Omri', 'Biton', 'Inactive', 7231.17, 'Shift Manager', 348);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (349, 'Maya', 'Biton', 'Inactive', 13231.46, 'Stock Clerk', 349);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (350, 'Dana', 'Dahan', 'Inactive', 11365.56, 'Department Manager', 350);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (351, 'Lior', 'Haddad', 'Inactive', 9294.66, 'Cashier', 351);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (352, 'Yael', 'Avraham', 'Inactive', 12157.03, 'Department Manager', 352);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (353, 'Dana', 'Cohen', 'Active', 16184.03, 'Department Manager', 353);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (354, 'Yarden', 'Cohen', 'Active', 6806.8, 'Department Manager', 354);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (355, 'Lior', 'Malka', 'Inactive', 17393.61, 'Cashier', 355);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (356, 'Eden', 'Mizrahi', 'Inactive', 17385.88, 'Shift Manager', 356);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (357, 'Yarden', 'Levi', 'Active', 12353.52, 'Stock Clerk', 357);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (358, 'Lior', 'Biton', 'Active', 17526.24, 'Cashier', 358);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (359, 'Dana', 'Dahan', 'Inactive', 16962.51, 'Cashier', 359);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (360, 'Maya', 'Biton', 'Inactive', 8574.85, 'Customer Service Representative', 360);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (361, 'Maya', 'Dahan', 'Active', 7471.65, 'Cashier', 361);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (362, 'Yarden', 'Mizrahi', 'Inactive', 17967.15, 'Department Manager', 362);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (363, 'Lior', 'Malka', 'Active', 12599.97, 'Shift Manager', 363);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (364, 'Maya', 'Mizrahi', 'Active', 15524.36, 'Customer Service Representative', 364);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (365, 'Roni', 'Levi', 'Active', 15504.79, 'Store Manager', 365);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (366, 'Yarden', 'Cohen', 'Inactive', 12648.26, 'Shift Manager', 366);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (367, 'Yarden', 'Amar', 'Active', 13343.38, 'Cashier', 367);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (368, 'Yael', 'Biton', 'Inactive', 17995.14, 'Department Manager', 368);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (369, 'Yarden', 'Amar', 'Inactive', 15229.97, 'Customer Service Representative', 369);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (370, 'Yael', 'Mizrahi', 'Inactive', 13708.06, 'Stock Clerk', 370);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (371, 'Yarden', 'Amar', 'Inactive', 7540.02, 'Customer Service Representative', 371);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (372, 'Eden', 'Mizrahi', 'Active', 11191.42, 'Cashier', 372);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (373, 'Yael', 'Amar', 'Active', 9649.49, 'Store Manager', 373);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (374, 'Lior', 'Peretz', 'Inactive', 17369.8, 'Customer Service Representative', 374);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (375, 'Maya', 'Levi', 'Inactive', 8355.62, 'Customer Service Representative', 375);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (376, 'Maya', 'Mizrahi', 'Inactive', 13373.14, 'Cashier', 376);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (377, 'Omri', 'Mizrahi', 'Active', 8054.41, 'Customer Service Representative', 377);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (378, 'Eden', 'Malka', 'Active', 15902.84, 'Cashier', 378);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (379, 'Yael', 'Cohen', 'Inactive', 13813.56, 'Customer Service Representative', 379);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (380, 'Neta', 'Haddad', 'Active', 11976.46, 'Department Manager', 380);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (381, 'Omri', 'Biton', 'Inactive', 11795.34, 'Department Manager', 381);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (382, 'Neta', 'Biton', 'Inactive', 6875.68, 'Cashier', 382);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (383, 'Dana', 'Dahan', 'Inactive', 11811.01, 'Store Manager', 383);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (384, 'Lior', 'Haddad', 'Active', 9750.99, 'Department Manager', 384);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (385, 'Lior', 'Malka', 'Inactive', 7569.19, 'Shift Manager', 385);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (386, 'Omri', 'Amar', 'Active', 9829.39, 'Stock Clerk', 386);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (387, 'Yael', 'Biton', 'Inactive', 8975.03, 'Cashier', 387);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (388, 'Noam', 'Biton', 'Inactive', 16369.97, 'Stock Clerk', 388);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (389, 'Roni', 'Mizrahi', 'Inactive', 17205.02, 'Department Manager', 389);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (390, 'Lior', 'Peretz', 'Active', 11979.19, 'Customer Service Representative', 390);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (391, 'Yarden', 'Dahan', 'Inactive', 11968.44, 'Cashier', 391);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (392, 'Neta', 'Amar', 'Inactive', 17600.24, 'Store Manager', 392);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (393, 'Eden', 'Malka', 'Active', 6606.48, 'Stock Clerk', 393);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (394, 'Eden', 'Dahan', 'Inactive', 12440.29, 'Cashier', 394);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (395, 'Neta', 'Mizrahi', 'Inactive', 14730.1, 'Stock Clerk', 395);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (396, 'Lior', 'Cohen', 'Inactive', 6613.89, 'Customer Service Representative', 396);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (397, 'Roni', 'Malka', 'Inactive', 6882.38, 'Customer Service Representative', 397);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (398, 'Yarden', 'Amar', 'Inactive', 15903.74, 'Customer Service Representative', 398);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (399, 'Eden', 'Levi', 'Active', 17700.99, 'Stock Clerk', 399);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (400, 'Lior', 'Malka', 'Inactive', 15059.58, 'Store Manager', 400);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (401, 'Eden', 'Amar', 'Inactive', 12000.93, 'Cashier', 401);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (402, 'Noam', 'Mizrahi', 'Inactive', 15647.59, 'Customer Service Representative', 402);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (403, 'Yarden', 'Mizrahi', 'Active', 9935.59, 'Customer Service Representative', 403);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (404, 'Lior', 'Mizrahi', 'Inactive', 17887.39, 'Department Manager', 404);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (405, 'Maya', 'Haddad', 'Inactive', 12087.78, 'Customer Service Representative', 405);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (406, 'Omri', 'Dahan', 'Inactive', 11698.71, 'Cashier', 406);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (407, 'Lior', 'Malka', 'Active', 17758.78, 'Customer Service Representative', 407);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (408, 'Maya', 'Cohen', 'Inactive', 9186.37, 'Department Manager', 408);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (409, 'Eden', 'Haddad', 'Active', 14656.8, 'Customer Service Representative', 409);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (410, 'Yarden', 'Mizrahi', 'Inactive', 7773.31, 'Department Manager', 410);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (411, 'Roni', 'Cohen', 'Active', 8289.41, 'Stock Clerk', 411);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (412, 'Lior', 'Avraham', 'Active', 10955.52, 'Store Manager', 412);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (413, 'Neta', 'Amar', 'Inactive', 16473.81, 'Department Manager', 413);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (414, 'Noam', 'Mizrahi', 'Active', 12730.64, 'Department Manager', 414);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (415, 'Yarden', 'Amar', 'Inactive', 9765.03, 'Store Manager', 415);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (416, 'Yarden', 'Amar', 'Inactive', 12555.28, 'Department Manager', 416);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (417, 'Maya', 'Haddad', 'Inactive', 8307.17, 'Store Manager', 417);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (418, 'Maya', 'Amar', 'Inactive', 8698.4, 'Shift Manager', 418);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (419, 'Maya', 'Peretz', 'Inactive', 9804.49, 'Shift Manager', 419);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (420, 'Omri', 'Biton', 'Inactive', 7462.49, 'Department Manager', 420);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (421, 'Omri', 'Avraham', 'Inactive', 15820.53, 'Store Manager', 421);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (422, 'Maya', 'Cohen', 'Inactive', 17463.76, 'Cashier', 422);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (423, 'Lior', 'Dahan', 'Inactive', 14968.06, 'Store Manager', 423);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (424, 'Roni', 'Amar', 'Inactive', 17196.29, 'Department Manager', 424);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (425, 'Maya', 'Mizrahi', 'Active', 13388.12, 'Customer Service Representative', 425);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (426, 'Roni', 'Peretz', 'Active', 14038.01, 'Customer Service Representative', 426);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (427, 'Roni', 'Peretz', 'Active', 7202.38, 'Shift Manager', 427);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (428, 'Yarden', 'Levi', 'Active', 6062.18, 'Customer Service Representative', 428);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (429, 'Dana', 'Avraham', 'Inactive', 11729.38, 'Store Manager', 429);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (430, 'Maya', 'Malka', 'Inactive', 13750.78, 'Cashier', 430);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (431, 'Eden', 'Peretz', 'Active', 16958.76, 'Store Manager', 431);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (432, 'Neta', 'Mizrahi', 'Active', 17966.06, 'Stock Clerk', 432);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (433, 'Yarden', 'Mizrahi', 'Inactive', 16520.92, 'Cashier', 433);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (434, 'Maya', 'Haddad', 'Active', 17141.46, 'Shift Manager', 434);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (435, 'Maya', 'Dahan', 'Inactive', 16671.12, 'Store Manager', 435);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (436, 'Omri', 'Dahan', 'Inactive', 8313.74, 'Cashier', 436);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (437, 'Lior', 'Mizrahi', 'Inactive', 13779.42, 'Department Manager', 437);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (438, 'Dana', 'Cohen', 'Inactive', 15489.21, 'Customer Service Representative', 438);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (439, 'Roni', 'Mizrahi', 'Inactive', 15923.88, 'Customer Service Representative', 439);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (440, 'Lior', 'Levi', 'Inactive', 14031.07, 'Store Manager', 440);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (441, 'Dana', 'Dahan', 'Inactive', 17229.9, 'Cashier', 441);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (442, 'Maya', 'Avraham', 'Active', 11360.83, 'Shift Manager', 442);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (443, 'Lior', 'Biton', 'Active', 9138.64, 'Shift Manager', 443);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (444, 'Roni', 'Cohen', 'Active', 11584.74, 'Store Manager', 444);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (445, 'Neta', 'Amar', 'Inactive', 14283.48, 'Department Manager', 445);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (446, 'Maya', 'Malka', 'Active', 8629.54, 'Store Manager', 446);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (447, 'Yarden', 'Mizrahi', 'Inactive', 14972.82, 'Customer Service Representative', 447);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (448, 'Lior', 'Avraham', 'Inactive', 15088.21, 'Department Manager', 448);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (449, 'Roni', 'Peretz', 'Active', 12306.08, 'Customer Service Representative', 449);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (450, 'Lior', 'Levi', 'Active', 6741.1, 'Customer Service Representative', 450);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (451, 'Omri', 'Peretz', 'Active', 7974.45, 'Customer Service Representative', 451);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (452, 'Yarden', 'Levi', 'Active', 14603.02, 'Stock Clerk', 452);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (453, 'Yael', 'Amar', 'Inactive', 15704.3, 'Stock Clerk', 453);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (454, 'Dana', 'Amar', 'Inactive', 11481.58, 'Cashier', 454);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (455, 'Omri', 'Dahan', 'Inactive', 14679.36, 'Stock Clerk', 455);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (456, 'Maya', 'Cohen', 'Active', 12939.74, 'Cashier', 456);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (457, 'Neta', 'Malka', 'Active', 12493.96, 'Cashier', 457);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (458, 'Yael', 'Dahan', 'Active', 9445.09, 'Store Manager', 458);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (459, 'Dana', 'Avraham', 'Inactive', 17914.28, 'Stock Clerk', 459);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (460, 'Yarden', 'Avraham', 'Inactive', 6963.0, 'Department Manager', 460);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (461, 'Omri', 'Mizrahi', 'Inactive', 7423.6, 'Customer Service Representative', 461);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (462, 'Neta', 'Amar', 'Active', 14734.3, 'Store Manager', 462);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (463, 'Noam', 'Cohen', 'Inactive', 11556.05, 'Department Manager', 463);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (464, 'Omri', 'Avraham', 'Inactive', 15880.33, 'Store Manager', 464);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (465, 'Yarden', 'Malka', 'Active', 9307.8, 'Department Manager', 465);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (466, 'Yael', 'Cohen', 'Inactive', 13379.08, 'Cashier', 466);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (467, 'Roni', 'Peretz', 'Active', 7210.76, 'Cashier', 467);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (468, 'Yarden', 'Haddad', 'Active', 8936.81, 'Cashier', 468);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (469, 'Neta', 'Dahan', 'Active', 12477.12, 'Cashier', 469);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (470, 'Dana', 'Amar', 'Inactive', 8809.94, 'Department Manager', 470);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (471, 'Eden', 'Malka', 'Inactive', 8842.85, 'Store Manager', 471);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (472, 'Omri', 'Peretz', 'Inactive', 9606.01, 'Cashier', 472);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (473, 'Omri', 'Haddad', 'Active', 13511.92, 'Stock Clerk', 473);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (474, 'Omri', 'Dahan', 'Active', 17667.48, 'Department Manager', 474);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (475, 'Neta', 'Amar', 'Inactive', 14355.7, 'Stock Clerk', 475);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (476, 'Dana', 'Biton', 'Inactive', 8206.55, 'Customer Service Representative', 476);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (477, 'Yarden', 'Peretz', 'Active', 9608.84, 'Department Manager', 477);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (478, 'Dana', 'Dahan', 'Active', 12748.63, 'Stock Clerk', 478);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (479, 'Omri', 'Amar', 'Active', 10661.03, 'Shift Manager', 479);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (480, 'Roni', 'Malka', 'Active', 17066.71, 'Shift Manager', 480);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (481, 'Yael', 'Amar', 'Active', 6618.44, 'Stock Clerk', 481);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (482, 'Eden', 'Haddad', 'Active', 16483.45, 'Store Manager', 482);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (483, 'Eden', 'Amar', 'Active', 11752.73, 'Shift Manager', 483);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (484, 'Maya', 'Cohen', 'Active', 17245.92, 'Department Manager', 484);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (485, 'Yael', 'Dahan', 'Active', 14347.52, 'Department Manager', 485);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (486, 'Roni', 'Avraham', 'Active', 12624.95, 'Shift Manager', 486);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (487, 'Neta', 'Dahan', 'Inactive', 9701.07, 'Shift Manager', 487);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (488, 'Omri', 'Dahan', 'Inactive', 7183.3, 'Department Manager', 488);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (489, 'Yarden', 'Malka', 'Active', 10448.46, 'Stock Clerk', 489);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (490, 'Noam', 'Haddad', 'Active', 14895.03, 'Cashier', 490);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (491, 'Maya', 'Amar', 'Inactive', 9542.31, 'Store Manager', 491);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (492, 'Lior', 'Peretz', 'Inactive', 12837.47, 'Store Manager', 492);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (493, 'Yarden', 'Amar', 'Inactive', 9087.92, 'Stock Clerk', 493);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (494, 'Yarden', 'Dahan', 'Active', 14793.27, 'Shift Manager', 494);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (495, 'Dana', 'Mizrahi', 'Inactive', 8208.57, 'Customer Service Representative', 495);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (496, 'Noam', 'Amar', 'Active', 16068.82, 'Cashier', 496);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (497, 'Noam', 'Cohen', 'Inactive', 7649.9, 'Department Manager', 497);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (498, 'Roni', 'Levi', 'Active', 6109.7, 'Customer Service Representative', 498);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (499, 'Yarden', 'Malka', 'Active', 13414.02, 'Department Manager', 499);
INSERT INTO EMPLOYEE (EmployeeID, FirstName, LastName, Status, Salary, Role, StoreID) VALUES (500, 'Eden', 'Dahan', 'Inactive', 6188.78, 'Customer Service Representative', 500);
