-- מחיקת טבלאות קשר (צומת) קודם
DROP TABLE IF EXISTS APPLIES_TO;
DROP TABLE IF EXISTS SUPPLIERED_BY;
DROP TABLE IF EXISTS INVENTORY;

-- מחיקת טבלאות עם Foreign Keys
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS EMPLOYEE;

-- מחיקת טבלאות אב (ללא תלויות)
DROP TABLE IF EXISTS DISCOUNT;
DROP TABLE IF EXISTS SUPPLIER;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS STORE;