CREATE TABLE STORE
(
  StoreID INT NOT NULL,
  StoreName VARCHAR(100) NOT NULL,
  Phone VARCHAR(15) NOT NULL,
  StoreEmail VARCHAR(100) NOT NULL,
  Rating INT NOT NULL,
  websiteurl TEXT,
  Address TEXT,
  Region VARCHAR(50),
  PRIMARY KEY (StoreID)
);

CREATE TABLE EMPLOYEE
(
  EmployeeID INT NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Status VARCHAR(20) NOT NULL, -- פעיל/לא פעיל
  Salary NUMERIC(10, 2) NOT NULL,
  Role VARCHAR(50) NOT NULL,
  StoreID INT NOT NULL,
  PRIMARY KEY (EmployeeID),
  FOREIGN KEY (StoreID) REFERENCES STORE(StoreID)
);

CREATE TABLE CATEGORY
(
  CategoryID INT NOT NULL,
  CategoryName VARCHAR(100) NOT NULL,
  IsActive INT NOT NULL, -- 1 לכן, 0 ללא
  PRIMARY KEY (CategoryID)
);

CREATE TABLE PRODUCT
(
  ProductID INT NOT NULL,
  ProductName VARCHAR(100) NOT NULL,
  Price NUMERIC(10, 2) NOT NULL,
  Brand VARCHAR(50) NOT NULL,
  ExpirationDate DATE NOT NULL, -- שימוש בטיפוס DATE כנדרש
  dateofmanufacture DATE,
  CategoryID INT NOT NULL,
  PRIMARY KEY (ProductID),
  FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID)
);

CREATE TABLE SUPPLIER
(
  SupplierID INT NOT NULL,
  SupplierName VARCHAR(100) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  ContactPhone VARCHAR(15) NOT NULL,
  Address VARCHAR(200) NOT NULL,
  PRIMARY KEY (SupplierID)
);

CREATE TABLE INVENTORY
(
  StoreID INT NOT NULL,
  ProductID INT NOT NULL,
  Quantity INT NOT NULL,
  MinimumStock INT NOT NULL,
  PRIMARY KEY (StoreID, ProductID),
  FOREIGN KEY (StoreID) REFERENCES STORE(StoreID),
  FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

CREATE TABLE DISCOUNT
(
  DiscountID INT NOT NULL,
  DiscountName VARCHAR(100) NOT NULL,
  DiscountPercentage INT NOT NULL,
  StartDate DATE NOT NULL, -- שימוש בטיפוס DATE כנדרש
  EndDate DATE NOT NULL,
  PRIMARY KEY (DiscountID)
);

CREATE TABLE WAREHOUSE
(
  WarehouseID INT NOT NULL,
  Region VARCHAR(50) NOT NULL,
  Address TEXT NOT NULL,
  PRIMARY KEY (WarehouseID)
);


CREATE TABLE DELIVERYCOMPANY
(
  DeliveryCieID INT NOT NULL,
  DeliveryCieName VARCHAR(100) NOT NULL,
  DeliveryCiePhoneNb VARCHAR(20) NOT NULL,
  Email VARCHAR(100) NOT NULL CHECK (Email LIKE '%@%'),
  PRIMARY KEY (DeliveryCieID),
  UNIQUE (DeliveryCieName),
  UNIQUE (DeliveryCiePhoneNb)
);

CREATE TABLE TRUCK
(
  DriverID INT NOT NULL,
  Active SMALLINT NOT NULL DEFAULT 1 CHECK (Active IN (0, 1)), 
  Capacity NUMERIC(10,2) NOT NULL CHECK (Capacity > 0),
  LicensePlate VARCHAR(20) NOT NULL,
  MaintenanceStatus VARCHAR(50) DEFAULT 'Good',
  DeliveryCieID INT NOT NULL,
  PRIMARY KEY (DriverID),
  FOREIGN KEY (DeliveryCieID) REFERENCES DELIVERYCOMPANY(DeliveryCieID),
  UNIQUE (LicensePlate)
);

CREATE TABLE "ORDER"
(
  OrderId INT NOT NULL,
  Price DECIMAL(10,2) NOT NULL CHECK (Price >= 0),
  DeliveryDate TIMESTAMP,
  OrderDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  StoreID INT NOT NULL,
  DriverID INT NOT NULL,
  PRIMARY KEY (OrderId),
  FOREIGN KEY (StoreID) REFERENCES STORE(StoreID),
  FOREIGN KEY (DriverID) REFERENCES TRUCK(DriverID)
);

CREATE TABLE PRODUCT_KASHRUT
(
  ProductID INT NOT NULL,
  Kashrut VARCHAR(50) NOT NULL,
  PRIMARY KEY (Kashrut, ProductID),
  FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE
);

CREATE TABLE WAREHOUSEMANAGER
(
  WarehouseID INT NOT NULL,
  WarehouseManager VARCHAR(100) NOT NULL,
  PRIMARY KEY (WarehouseManager, WarehouseID),
  FOREIGN KEY (WarehouseID) REFERENCES WAREHOUSE(WarehouseID) ON DELETE CASCADE
);

CREATE TABLE DELIVERYCOMPANY_REGIONSERVED
(
  DeliveryCieID INT NOT NULL,
  RegionServed VARCHAR(50) NOT NULL,
  PRIMARY KEY (RegionServed, DeliveryCieID),
  FOREIGN KEY (DeliveryCieID) REFERENCES DELIVERYCOMPANY(DeliveryCieID) ON DELETE CASCADE
);

CREATE TABLE SUPPLIERED_BY
(
  SupplierID INT NOT NULL,
  ProductID INT NOT NULL,
  PRIMARY KEY (SupplierID, ProductID),
  FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID),
  FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

CREATE TABLE APPLIES_TO
(
  ProductID INT NOT NULL,
  DiscountID INT NOT NULL,
  PRIMARY KEY (ProductID, DiscountID),
  FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
  FOREIGN KEY (DiscountID) REFERENCES DISCOUNT(DiscountID)
);

CREATE TABLE CONTAINS
(
  OrderId INT NOT NULL,
  ProductID INT NOT NULL,
  Quantity INT NOT NULL DEFAULT 1 CHECK (Quantity > 0),
  PRIMARY KEY (OrderId, ProductID),
  FOREIGN KEY (OrderId) REFERENCES "ORDER"(OrderId) ON DELETE CASCADE,
  FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

CREATE TABLE LOCATED
(
  ProductID INT NOT NULL,
  WarehouseID INT NOT NULL,
  AisleNb INT NOT NULL CHECK (AisleNb > 0),
  ShelfNb INT NOT NULL CHECK (ShelfNb > 0),
  PRIMARY KEY (ProductID, WarehouseID),
  FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
  FOREIGN KEY (WarehouseID) REFERENCES WAREHOUSE(WarehouseID)
);












































